### ISSUE TITLE
[QUESTION] will skia work in UWP ARM64 architecture?

### ISSUE THREAD

**Issue by JeganSyncfusion** [mono/SkiaSharp#1071]
will skia work in UWP ARM64 architecture?

**Comment by mattleibow** [comment]
Yes and no.

No for right now because the current set of packages are based on fairly old builds.

Yes for in a bit. Right now we have an old build system. We need to update to VS2019 (#1030). That just does the managed part, but I'm working on the PR for the native bits. Shouldn't be too hard, just haven't gotten to it yet.

**Comment by mattleibow** [comment]
I think we can do this for v1.68.2

**Comment by cghersi** [comment]
Do you have a tentative date for when the ARM64 support will be available?

**Comment by mattleibow** [comment]
I tried having a look at ARM64 for the current versions of skia, but there are several things that will need to change - the MSVC version, drop some older platforms, build ANGLE, etc. But, the version that is currently being targeted/merged does already have ARM64 support: https://github.com/mono/SkiaSharp/pull/986

I can't say exactly when this will get pushed out. I am hoping to get this out in a month or so, but as a result of the number of breaking changes, may take a bit longer.

At the end of the day, the time to make v1.68.x use ARM64 will not really be useful since that is going to be replaced by a fairly different v2.80.x.

**Comment by vijayasurya20** [comment]
Hi @mattleibow ,

Thank you for your update.

Can you please share me the expected release timeline for this SkiaSharp support in ARM64 architecture? 

Regards,
Vijayasurya A

**Comment by mattleibow** [comment]
Things are a bit flexible, but we are aiming for the first previews in March/April. At this time, there are bits that are working, but unfortunately in our work, we removed a whole bunch of types and members to get it to compile. I am right now working to make sure that the API is backwards compatible. This is taking a bit of time as certain things will have to be reworked internally.

A rough estimate is that we will have previews sometime in March.

**Comment by ManishSync** [comment]
Hi @mattleibow,

Can you please share with me the expected release timeline for this SkiaSharp support in ARM64 architecture?

Regards,
Manikandan R

**Comment by mattleibow** [comment]
I forgot to update this issue with the numbers 😢 The alphas are out on the preview feed: https://aka.ms/skiasharp-eap/index.json

Check out the v2.80.x versions, but the most recent is **v2.80.0-alpha.8**.

This should have ARM64 for UWP.

**Comment by johnsonmanickam** [comment]
Thanks for the updates. When will be the package available in NuGet.org? Any timeline?

**Comment by mattleibow** [comment]
Merged and on nuget.org.
