### ISSUE TITLE
[BUG] unable to use with Xamarin.Forms 4.2 and above

### ISSUE THREAD

**Issue by VladislavAntonyuk** [mono/SkiaSharp#1106]
https://github.com/xamarin/Xamarin.Forms/issues/9129

**Comment by mattleibow** [comment]
@VladislavAntonyuk Thanks for opening this issue. I'll update the preview ASAP.

**Comment by mattleibow** [comment]
Work has been done, features been added, previews published. Check out the brand new preview (1.68.2-preview.29) that just left the gates! https://github.com/mono/SkiaSharp/releases/tag/v1.68.2-preview.29

This issue is fixed, but a similar one, #1113, is still being looked at. Xamarin.Forms 4.4+ seems to be having issues in UWP. As long as you aren't using the `SK*ImageSource` types on Tizen, this should be fine. I hope to get that fixed ASAP.

**Comment by mattleibow** [comment]
Fixed again for a different reason in #1117
