### ISSUE TITLE
[QUESTION] Trying to get Accord.NET to work with SkiaSharp

### ISSUE THREAD

**Issue by TheBricktop** [mono/SkiaSharp#1171]
I want to use Accord.net in unity on android app.
Since Accord.Net is the only netCore opencv competitor this should be almost trivial task since it works almost on any cpu. But there is one caveat - it relies on dreaded System.Drawing for things  like image operations and color structs and image filtering.
That locks the visual side of the Accord on windows only.
I want to replace the System.Drawing namespace with skiasharp one with something like a glue code that translates the system.drawing types to the skias references.
For example Bitmap class should inherit from SKBitmap and Color from SKColor (or implement similar methods)
Is this viable ? I dont want to recompile whole Accord lib just to get some functions but this will prolly be this way.

**Comment by mattleibow** [comment]
Hmm. This has been sort of in my mind. There is that https://www.nuget.org/packages/System.Drawing.Common package that might help. You could also create a stub library that just has the members you need and wrap SkiaSharp.

Maybe you can open an issue as well on accord.net to see if they are interested in using SkiaSharp officially. Then we can get better cross-platform support.

**Comment by TheBricktop** [comment]
while i was trying to use system.drawing.commons in unity but failed miserably mostly because there were some problems with Bitmap class, also it seems that it doesn't containt xamarin.android build

**Comment by TheBricktop** [comment]
im also asking if creating a dummy System.Drawing namespace where all classes are inheriting from skias is a good approach?

**Comment by mattleibow** [comment]
I am not sure the inheritance is  good thing due to the objects having different purposes as well as conflicting members. I would create wrapper classes instead. In the case of System Bitmap/Image, this is not really a 1:1 mapping of SKBitmap/SKImage. The SKImage is a snapshot, the SKBitmap is editable.

I would set up your version of stubbed System.Drawing, and then implement the members you need using SkiaSharp under the hood. 

All the source is here, so you can copy ABI and tests: https://github.com/dotnet/runtime/tree/master/src/libraries/System.Drawing.Common
Also, you can make use of the GenAPI tool here (from MS) to generate the APIs and then you don't even have to write it yourself: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-eng&package=Microsoft.DotNet.GenAPI&protocolType=NuGet&version=5.0.0-beta.20164.1

If you create a project for this (or get started on it) then this will be a HUGE help to the community. I'll also ask on Twitter to see if someone has done this already...

**Comment by TheBricktop** [comment]
Never made any wrapper class before is there any good guide for this ?

**Comment by mattleibow** [comment]
This is sort of a per-project design. But, this is just more a way of doing things:

```csharp
class Graphics {
    SKSurface surface;
    void DrawImage(Image image, Point point) {
        surface.DrawImage(image.skiaPitmap, point.ToSKPoint())
    }
}

class Image {
    SKBitmap skiaBitmap;
}
```

**Comment by TheBricktop** [comment]
welll im just starting a project to combine accordNet skia and unity in one project 
https://github.com/InstytutXR/AccordNET4Unity

**Comment by mattleibow** [comment]
Closing this issue as it does not directly pertain to the SkiaSharp library development.
