### ISSUE TITLE
[FEATURE] DeviceType Support for SKView Touch Events to support stylus

### ISSUE THREAD

**Issue by mscherotter** [mono/SkiaSharp#1186]
SkiaSharp canvas view events always have touch device type even when touched with a pen.

SkCanvasView.OnTouch() events:
SKTouchEventArgs has a Touch device type which always registers as a “touch” event. on Android at

https://github.com/mono/SkiaSharp/blob/b8511b732b77b6e9f3b4929a5fa5598d189adf1d/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs

The event is being created using the constructor that doesn’t have the device ID :

```
var args = new SKTouchEventArgs(id, SKTouchAction.Pressed, coords, true);
``` 

Which is then defaulting to touch:
 
```
public SKTouchEventArgs(long id, SKTouchAction type, SKPoint location, bool inContact)
    : this(id, type, SKMouseButton.Left, SKTouchDeviceType.Touch, location, inContact, 0)
{
}
```

**Describe the solution you'd like**
in the SkTouchHandler.OnTouch, set the SkTouchEventArgs DeviceType based on the MotionEvent device type.
You can find the type under the motionevent property of the args then calling GetToolType on it 
https://docs.microsoft.com/en-us/dotnet/api/android.views.motionevent.gettooltype?view=xamarin-android-sdk-9#Android_Views_MotionEvent_GetToolType_System_Int32_

**Describe alternatives you've considered**
none found

**Additional context**
none

**Comment by mattleibow** [comment]
This is a good idea to add. It looks like you already did some research, so you may have some ideas and code already. If so, just open a PR and we can talk code.

We don't have this feature yet just because I never did it. And nobody asked. But now you have 😄 

That `MotionEvent.GetToolType(int)` member seems to be a API 14+ member, so you might just need to wrap it in a OS version check. But we can add that after we got the code actually working - just in case we have to adjust things. Or you can do it all in one go.

Anyways, from the looks of things, you should just be able to get the tool type and then use the overload that takes it.

If you are interested in writing the code, then just go ahead and try out things, open a PR and then you can add PR comments or start a discussion.

Oh, and thanks for the issue and the initial research.

**Comment by mattleibow** [comment]
This is now out on NuGet as **1.68.2-preview.50**
