### ISSUE TITLE
Add SVG support to SkiaSharp

### ISSUE THREAD

**Issue by Emasoft** [mono/SkiaSharp#120]
I think that full SVG support should be added to the SkiaSharp library, including SVG Animations ( https://svgwg.org/specs/animations/ ). 

If SkiaSharp is going to be the engine behind Xamarin.Forms (and the whole WPF crossplatform), then SVG support is as necessary as PNG or JPG support. 
You cannot treat SVG as a external option, something that you can delegate to a secondary framework made by amateurs.
It is the main vector image format around. 90% of all vector graphic resources (icons, graphic elements, UI skins, animations, backgrounds, etc...) are made in SVG, exported in SVG and distributed in SVG. Artists and designers are used to save their vector images in SVG format. App design tools like Sketch or AdobeXD export the app design storyboards as SVG files, ready to be imported in the app. Popular mobile apps like Viber use SVG SMIL animations extensively for ALL their awesome animated stickers. With the advent of the modern high density display jungle, everybody is dropping bitmap assets for SVG assets.
Intro animations for the "Onboarding" phase of new apps are now often made with SVG SMIL animated clips. The new popular SVG morphing algorithms are now used by many design tools to create animated visual transitions easily between UI states, just by choosing a start and an end SVG image. From those two inbetweens are automatically generated at 60 fps, for a smooth and modern UI.
No vector framework is going to succeed with developers without SVG support, no more than a bitmap imaging framework without PNG or JPG support. Other crossplatform 2D libraries like NGraphics for example already support SVG.
This is very urgent, otherwise Xamarin.Forms is going to be more and more detached from the needs of modern app development.

**Comment by gentledepp** [comment]
It is also my opinion, that SVG is a very important frontend (I believe it is called this way in Skia?).

We are already creating our own port of a SVG library using SkiaSharp.
However, our goal is to have a vector-graphics based editor for mobile platforms. 
So advanced animations and filters will not be provided by us and also, as it is not native and includes all the callbacks and a rather compliated object model, it surely won't be fast enough for the purposes mentioned by @Emasoft 

Nevertheless, you guys are doing a great job! I really love SkiaSharp. It even made me try to work with C++ and C again ;-)

**Comment by migueldeicaza** [comment]
SVG is not supported by Skia itself, and thus is outside the scope of this project.

Nothing is preventing an additional library from being created that can load SVG files, but it is not part of the SkiaSharp project, unless you get Google to add SVG support directly to Skia.   Which is rather unlikely for reasons stated somewhere else on the bug reporting system.

**Comment by gentledepp** [comment]
That is a good point, @migueldeicaza.
Nevertheless, it would be a superb addition to the Xamarin toolset.
As I am not planning to work fulltime on our SVG port, we will, however, never implement things as animations and the like.
Also, as it is a full blown SVG rendering **and editing** framework, it will never be as fast as a pure render lib. But I would be very happy to see our efforts supported by you :)

**Comment by Emasoft** [comment]
@gentledepp Unfortunately I think that Skia is a dead end. I don't know why Miguel picked it, but nobody uses it on Android anymore because it is not hardware accelerated. We need an hardware accelerated crossplatform solution, like NGraphics (it uses the native calls of iOS and Android sdk, that are hardware accelerated), not an old and slow lib like Skia. 
If I were in Miguel, I'll buy NGraphics and I'll start developing a cross platform WPF implementation with it, so that XAML code in Xamarin.Forms would be the same on all platforms, and SVG support in Xamarin.Forms would be obtained as a bonus.
Currently Xamarin.Forms is too slow (even using the XAMLC), and you need hacks like the TwinTechs FastCell library to get a decent listview scroll speed.
Porting Skia to C# as a Xamarin library is a waste of time. Miguel should just hire Fred Kruger and some other developer like you, and start to invest in NGraphics as the next backbone of Xamarin.Forms.

**Comment by mattleibow** [comment]
@emasoft, skia is hardware accelerated, but we have not yet brought that up to the C# binding layer. We were focussing on bringing functionality and features.

**Comment by migueldeicaza** [comment]
There are many incorrect statements made about SkiaSharp on @Emasoft 's previous comment.  This sort of misinformation is not helpful, here are some corrections to clear the record:

* Everyone uses Skia on Android, it is the graphics library that powers every drawing call on Android.

* Further, it is the engine that powers Google Chrome.

* Hardware acceleration for 2D has limitations compared to the expectations of most people.   Including CoreGraphics, where only a handful of operations are hardware accelerated.   

* When NGraphics delegates to the native code on Android, it is delegating to the system installed version of Skia

* When NGraphics delegates to native code on iOS, it delegates to CoreGraphics, which only has support for doing some hardware acceleration (layer composition to a large extent, the rest is software rendered).

* Support for GPU primitives in Skia is something we have not bound.

* SkiaSharp is not a C# port of the native API, it is a wrapper of the native API.

* SVG support is an independent effort from SkiaSharp, as stated on the comemnts.

* Xamarin.Forms does not use SkiaSharp, so it is irrelevant to this discussion.

For the purpose of letting emotions cool off, I am adding a temporary ban for Emasoft for more comments.

**Comment by gentledepp** [comment]
Thank you for making this clear. I personally am totally amazed by your
efforts.
You guys are doing a great job :-)

Am 02.08.2016 21:52 schrieb "Miguel de Icaza" <notifications@github.com>:

There are many incorrect statements made about SkiaSharp on @Emasoft
<https://github.com/Emasoft> 's previous comment. This sort of
misinformation is not helpful, here are some corrections to clear the
record:

   -

   Everyone uses Skia on Android, it is the graphics library that powers
   every drawing call on Android.
   -

   Further, it is the engine that powers Google Chrome.
   -

   Hardware acceleration for 2D has limitations compared to the
   expectations of most people. Including CoreGraphics, where only a handful
   of operations are hardware accelerated.
   -

   When NGraphics delegates to the native code on Android, it is delegating
   to the system installed version of Skia
   -

   When NGraphics delegates to native code on iOS, it delegates to
   CoreGraphics, which only has support for doing some hardware acceleration
   (layer composition to a large extent, the rest is software rendered).
   -

   Support for GPU primitives in Skia is something we have not bound.
   -

   SkiaSharp is not a C# port of the native API, it is a wrapper of the
   native API.
   -

   SVG support is an independent effort from SkiaSharp, as stated on the
   comemnts.
   -

   Xamarin.Forms does not use SkiaSharp, so it is irrelevant to this
   discussion.

For the purpose of letting emotions cool off, I am adding a temporary ban
for Emasoft for more comments.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mono/SkiaSharp/issues/120#issuecomment-237022955>, or mute
the thread

**Comment by migueldeicaza** [comment]
Svg support is now available as SkiaSharp.Svg

**Comment by danwalmsley** [comment]
https://github.com/wieslawsoltes/Svg.Skia
