### ISSUE TITLE
[QUESTION] How to get bitmap cropped by any quadrangle

### ISSUE THREAD

**Issue by dsadlowski** [mono/SkiaSharp#1231]
Hello.

Is it possible to cut a bitmap fragment from the quadrangle, which is marked with four points?
I create app which take a photo and then allow user to crop that image. But user can create a non rectangle shapes. I know i need to do a matrix transformation to return normal image but i don't know how to get specific part of bitmap to transform

<img src="https://user-images.githubusercontent.com/63102347/79326609-6abb7e00-7f13-11ea-81d8-ed8ac632b0b4.png" width="300" />

Can u help me?
Thanks in advance for the answer.

**Comment by mattleibow** [comment]
This is pretty easy to do, once you have the image and the path that you wish to crop, create a new surface, clip and draw.

I have an example app here:
https://github.com/mattleibow/SkiaSharpImageCropper/blob/master/ImageCropper/ImageCropper/MainPage.xaml.cs#L104

**Comment by Ziriax** [comment]
Do you also want to apply a perspective transformation to the cropped polygon, so that the polygon is transformed into a square?

If so, it seems SkiaSharp 1.68 is currently missing some Skia/C++ methods to create a perspective matrix that maps a quadrilateral to another quadrilateral, e.g. [the `setPolyToPoly` method](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/src/core/SkMatrix.cpp;l=1417?q=setPolyToPoly)

If need that, you could convert [this C++ code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/src/core/SkMatrix.cpp;drc=da6ef73266f6110abc5e788457f0e8f9257dd5b6;l=1341?q=setPolyToPoly) to C# for now

**Comment by dsadlowski** [comment]
Thank you for replies.
This is exactly what i looking for. Works great!
