### ISSUE TITLE
Unable to load PNG bitmap with SKColorType.Index8 color

### ISSUE THREAD

**Issue by wieslawsoltes** [mono/SkiaSharp#128]
Version: 1.53.0, Windows 10 x64, VS2015 Update 3

Hi, I have run into issue with `SKBitmap` in latest `SkiaSharp`, when the source bitmap has `SkiaSharp.SKColorType.Index8` than I get error as result `SkiaSharp.SKCodecResult.InvalidConversion`.

Code to reproduce:
```C#
        public IBitmapImpl LoadBitmap(System.IO.Stream stream)
        {
            using (var s = new SKManagedStream(stream))
            {
                using (var codec = SKCodec.Create(s))
                {
                    var info = codec.Info;
                    var bitmap = new SKBitmap(info.Width, info.Height, info.ColorType /*SKImageInfo.PlatformColorType*/, info.IsOpaque ? SKAlphaType.Opaque : SKAlphaType.Premul);

                    IntPtr length;
                    var result = codec.GetPixels(bitmap.Info, bitmap.GetPixels(out length));
                    if (result == SKCodecResult.Success || result == SKCodecResult.IncompleteInput)
                    {
                        return new BitmapImpl(bitmap);
                    }
                    else
                    {
                        throw new ArgumentException("Unable to load bitmap from provided data");
                    }
                }
            }
        }
```

And the bitmap:
![github_icon](https://cloud.githubusercontent.com/assets/2297442/17378234/64eb408e-59bd-11e6-8b5b-81dad488d253.png)

When I change from` info.ColorType` to `SKImageInfo.PlatformColorType` all works as expected. This image was loading correctly in previous version.

**Comment by bholmes** [comment]
To clarify.  This has only been tested (running) on Windows 10 so far.  The behavior may exist on other platforms.

**Comment by wieslawsoltes** [comment]
This also happens on AppVeyor CI when using `SKBitmap.Decode` method. To fix the issue this patch has been made: https://github.com/AvaloniaUI/Avalonia/commit/126c28862d8464f16eea2de8a1a53eb3affd2f49

**Comment by mattleibow** [comment]
@wieslawsoltes @bholmes the reason for this is in the C++ code:
https://github.com/mono/skia/blob/c8265a162d096951564ecb48cb789a97c03dc690/src/core/SkBitmap.cpp#L287
```cpp
bool SkBitmap::tryAllocPixels(const SkImageInfo& requestedInfo, size_t rowBytes) { 
   if (kIndex_8_SkColorType == requestedInfo.colorType()) { 
        return reset_return_false(this); 
    }
```

This version of "new SKBitmap" in C# uses this C++ method, which does not handle `Index8`. The reason is that `Index8` requires that the color table to be set. As the colors are index based, we need the color table.

I will need to look into creating a bitmap with an Index8 color type. But I think in this instance, using BGRA8888 or RGBA8888 should be fine for on-screen drawing. I may be wrong, but Index8 is more for image storage on disk. No point in storing 4 bytes/pixel when 1 byte can do. This can be seen in the image provided, which is 18 KB as is, but goes up to 24 KB when saved as a 32-bit image instead of an 8-bit image.

**Comment by mattleibow** [comment]
@gentledepp, I think I have all the bits covered now:
https://github.com/mono/SkiaSharp/blob/a2cae9245fb73281d8d5f193210a92fe21613a6d/binding/Binding/SKBitmap.cs#L263-L284

You can test it out and see how it all works.

**Comment by gentledepp** [comment]
I am confused. I did not report this big, neither did I stumble across it. What am I missing? :-)

**Comment by wieslawsoltes** [comment]
@mattleibow I am using SkiaSharp via NuGet so I cant test this.

**Comment by mattleibow** [comment]
@gentledepp Oops, wrong guy 😜  You are my favourite user, so don't tell anybody 😉

**Comment by gentledepp** [comment]
Should I be concerned? :-D

Am 04.08.2016 20:57 schrieb "Matthew Leibowitz" <notifications@github.com>:
