### ISSUE TITLE
[BUG] WPF crash on SKImage use

### ISSUE THREAD

**Issue by VladislavAntonyuk** [mono/SkiaSharp#1284]
**Description**

app crashes with the error: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Code**

var image = SKImage.Create(new SKImageInfo(CaptchaLength * textSize, textSize, SKColorType.Argb4444));
       

**Expected Behavior**

**Actual Behavior**

**Basic Information**

- Version with issue:  2.80.0-alpha.4
- Last known good version:  1.68.2....
- Platform Target Frameworks: 
  - WPF: net462

Issue is reproduced only if use 64bit

**Comment by mattleibow** [comment]
You might be having an issue with the assembly being loaded/run by a 32-bit process.

Check out this issue: https://github.com/mono/SkiaSharp/issues/513

**Comment by VladislavAntonyuk** [comment]
@mattleibow so SkiaSharp only support x86? it is not build for x64?
Can I use Prefer32bit as false, and set `<PreferredNativeSkiaSharp>x86</PreferredNativeSkiaSharp>`?

**Comment by Gillibald** [comment]
Just don't compile for AnyCpu and instead specify the arch explicitly. This is more an issue of the tooling.

**Comment by mattleibow** [comment]
If `<Prefer32bit>` is false, then you need to use `x64` on 64-bit runtime - which is the default on Windows nowadays. But, yeah, Any CPU has issues.

However, I would suggest using the new netcoreapp3.0 with WPF instead of the older net462. Then, not only do you get the inherent .NET Core performance improvements, but also you will never have to worry abut this again. .NET Core gets all the native runtimes right.

**Comment by VladislavAntonyuk** [comment]
@mattleibow I use netcoreapp5.0, but it has an issue with Xamarin Forms, so I temporary switched to net462
