### ISSUE TITLE
NullReferenceException in SKCodec.Create()

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#131]
With SkiaSharp HEAD, I am trying to create an `SKBitmap` from a `System.Drawing.Bitmap` instance like this:

```
public static SKBitmap SKBitmapFromBitmap(System.Drawing.Bitmap bitmap) {
    using (System.IO.MemoryStream memstr = new System.IO.MemoryStream()) {
        bitmap.Save(memstr, bitmap.RawFormat);
        using (var s = new SKManagedStream(memstr)) {
            using (var codec = SKCodec.Create(s)) {
                var info = codec.Info;
                var skbitmap = new SKBitmap(info.Width, info.Height, SKImageInfo.PlatformColorType, info.IsOpaque ? SKAlphaType.Opaque : SKAlphaType.Premul);
                IntPtr length;
                var result = codec.GetPixels(skbitmap.Info, skbitmap.GetPixels(out length));
                if (result == SKCodecResult.Success) {
                    return skbitmap;
                } else {
                    throw new ArgumentException();
                }
            }
        }
    }
}
```

But during the `SKCodec.Create(s)` call I am getting a NullReferenceException at SKCodec.cs [line 142](https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKCodec.cs#L142). Stepping through in the debugger, it appears `GetObject<SKCodec>(...)` is returning null. Note that `stream.Handle` is 0, presumably because it's a managed stream.

Am I doing something wrong in creating the SKBitmap? I'm basing my code off of the sample code [BitmapDecoder](https://github.com/mono/SkiaSharp/blob/master/samples/SharedDemo/SkiaSharp.Demos.cs#L499).

**Comment by mattleibow** [comment]
@tdenniston Thanks for creating an issue. There is no real problem with your code except that you are reading a stream when the position is already at the end (after the `bitmap.Save` operation).
To fix this, just flush and rewind:

```csharp
// ...
bitmap.Save(memstr, bitmap.RawFormat);
// rewind the stream
memstr.Flush();
memstr.Position = 0;
// ...
```

What is happening is that you are saving, and when the codec tries to read it, it is unable to get data since there is no more data after the current position. As a result, the codec is returned as `null`. Internally we assume it will never be `null` (which is wrong), and thus the `NullReferenceException`.

`stream.Handle` is `0` due to the fact that the `SKCodec` takes ownership of the stream in native code and then disposes and releases the memory. As a result, the handle is `0` or `NULL`.

I have made a small change in our code to prevent an exception, and it should just return `null` as expected. However, the correct way to use these types is to first rewind the **`MemoryStream`**. `SKManagedStream` will always have its own start at the position of the provided stream.

**Comment by mattleibow** [comment]
Improved the ownership management: https://github.com/mono/SkiaSharp/commit/8239f1670e1f733167e853ab1900f97629a7cdc5

**Comment by tdenniston** [comment]
Confirmed that adding the `Flush()` and `Position = 0` fixes my issue. Thanks for responding so quickly!
