### ISSUE TITLE
Unable to load shared library 'libSkiaSharp' or one of its dependencies - azure app service on Linux

### ISSUE THREAD

**Issue by tbasallo** [mono/SkiaSharp#1341]
**Description**

Just like the bug that was closed #1312 . Except this one is not using any other external libs, it's just the Skia code.

A page that accesses Skia on Azure Linux fails. The same page on Windows desktop or Azure runs fine.

**Exception**
```
DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
SkiaSharp.SkiaApi.sk_managedstream_set_procs(SKManagedStreamDelegates procs)

TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception.
SkiaSharp.SKAbstractManagedStream..ctor(bool owns)
```
**Raw**
```
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_managedstream_set_procs(SKManagedStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedStream..cctor()


```

    <PackageReference Include="Azure.Cosmos" Version="4.0.0-preview3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.5" />
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="2.0.0-preview" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3" />
    <PackageReference Include="Azure.ImageOptimizer" Version="1.1.0.39" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.5.0-preview.1" />
    <PackageReference Include="SkiaSharp" Version="2.80.0-preview.14" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.0-preview.14" />

- Version with issue: Both  1.6 and 2.8 preview (NUGET)
- IDE: VS2019
- Core 3.1, Azure Linux App Service

**Comment by mattleibow** [comment]
Most likely you don't have the FontConfig dependency for Linux. This needs to be installed via the platform tooling (apk or apt-get).

There is also the `SkiaSharp.NativeAssets.Linux.NoDependencies` that you can use instead of `SkiaSharp.NativeAssets.Linux` to avoid this, but you lose out on some advanced font features.

This usually does it for me:

```
sudo apt-get install -y libfontconfig1
```

**Comment by tbasallo** [comment]
Since this is Azure Linux App Service users cannot install anything.

I'll try the NoDependencies since this purely image based, no fonts, which I'm assuming is text functions. I'll report back.

**Comment by mattleibow** [comment]
The other option is just to use Docker services.

**Comment by mattleibow** [comment]
Did you manage to resolve this?

**Comment by JMan7777** [comment]
Hi,

I'm running a Linux Web App in Azure (docker container based on the Alpine 3.11 image from MS)

Even I use the `SkiaSharp.NativeAssets.Linux.NoDependencies` package (version 2.80.1) I still get the exception:

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
2020-07-17T03:14:17.499823180Z: [INFO]   ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory
2020-07-17T03:14:17.499830080Z: [INFO]     at SkiaSharp.SkiaApi.sk_data_new_empty()
2020-07-17T03:14:17.499834080Z: [INFO]     at SkiaSharp.SKData..cctor()
2020-07-17T03:14:17.499837980Z: [INFO]     --- End of inner exception stack trace ---
2020-07-17T03:14:17.499841880Z: [INFO]     at SkiaSharp.SKData.Create(Stream stream)
2020-07-17T03:14:17.499846880Z: [INFO]     at SkiaSharp.SKImage.FromEncodedData(Stream data)
```

I use the following base image:
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.11 AS base`
and add the icu-libs package:
`RUN apk add --no-cache icu-libs`

Are there any other packages required?

**Comment by mattleibow** [comment]
@JMan7777 I had a look at this and I found the issue. Thanks for reporting.

The bug:
For some reason the Alpine build of no dependencies is still building with fontconfig. I have checks in CI for this, but it missed this? Not sure at this time. I will investigate and get a fix out ASAP.

The workaround:
Install `fontconfig` (not icu): `RUN apk add --no-cache fontconfig`

However, if you _can_ install fontconfig on your systems, then it might be better to just use the plain `SkiaSharp.NativeAssets.Linux` package as that has better font features.

Apologies for this. I'll have a look at the build tests to determine why this got through and ensure it does not happen again.

**Comment by mattleibow** [comment]
The way you can debug this is to either do:

`ldd libSkiaSharp.so`

or 

`readelf -d libSkiaSharp.so`

**Comment by mattleibow** [comment]
I got a fix going out with 2.80.2. Thanks for reporting.

**Comment by JMan7777** [comment]
Thx a lot.

Do we still need the icu-libs package for the NoDependencies version?

**Comment by mattleibow** [comment]
No. We don't need the icu at all. We are using harfbuzz, but that is in a separate NuGet as an option. Not required.

**Comment by IsoraTatsu** [comment]
`"System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.\n ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory\n   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()\n   at SkiaSharp.SKImageInfo..cctor()\n   --- End of inner exception stack trace ---\n   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)\n   at SkiaSharp.QrCode.Image.QrCode..ctor(String content, Vector2Slim qrSize)\n   at SkiaSharp.QrCode.Image.QrCode..ctor(String content, Vector2Slim qrSize, SKEncodedImageFormat outputFormat)\n   at HMS.Mobile.Vinpearl.Common.Services.BookingService.GetQRCodeBase64String(String itineraryNumber, String roomConfirmationNumber, String roomCancellationNumber, DateTime arrivalDate) in \/src\/HMS.Mobile.Vinpearl.Common\/Services\/BookingService.cs:line 137"`
how about my issue.

**Comment by IsoraTatsu** [comment]
**Exception**
`System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.\n ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory\n   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()\n   at SkiaSharp.SKImageInfo..cctor()\n   --- End of inner exception stack trace ---\n   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)\n   at SkiaSharp.QrCode.Image.QrCode..ctor(String content, Vector2Slim qrSize)\n   at SkiaSharp.QrCode.Image.QrCode..ctor(String content, Vector2Slim qrSize, SKEncodedImageFormat outputFormat)\n   at ...`

` <PackageReference Include="SkiaSharp.QrCode" Version="0.3.2" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.1" />`

.net core 2.1, aws linux
Version with issue: 2.80.1

I had try to fix by
[https://github.com/mono/SkiaSharp/issues/964](url) but didn't work

**Comment by mattleibow** [comment]
@IsoraTatsu  This was unfortunately a regression in 2.80.x that will be fix in the next version coming soon

You can try out `2.80.2-preview.2` right now on the preview feed: https://aka.ms/skiasharp-eap/index.json 

I will be pushing this version to nuget.org very soon.

**Comment by IsoraTatsu** [comment]
tks

**Comment by srinathck** [comment]
I still have this issue. Using 2.80.2-preview-33.

**Comment by mattleibow** [comment]
Could you have a look at preview 36 that was just pushed out. I think we fix an issue that was coming up for web apps.

**Comment by hewisaurus** [comment]
I'm still having this issue using `SkiaSharp.NativeAssets.Linux.NoDependencies 2.80.2`.
Was there anything specific that others did to get this working?

**Comment by mattleibow** [comment]
There should not be anything.

I just checked, the only dependencies are:

```
Shared library: [libpthread.so.0]
Shared library: [libdl.so.2]
Shared library: [libm.so.6]
Shared library: [libc.so.6]
Shared library: [ld-linux-x86-64.so.2]
```

**Comment by mattleibow** [comment]
Did the latest release fix this issue for anyone else?

**Comment by jaliyaudagedara** [comment]
I am facing this issue:

Environment: Azure Durable Function on Linux

Trying to convert a Docx to PDF using Syncfusion.

```
<PackageReference Include="SkiaSharp" Version="2.80.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />
<PackageReference Include="Syncfusion.DocIO.Net.Core" Version="18.2.0.58" />
<PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="18.2.0.58" />
```

Error:
```
System.DllNotFoundException at SkiaSharp.SkiaApi.sk_colortype_get_default_8888

Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory.
--

**Comment by mattleibow** [comment]
What happens when you remove SkiaSharp.NativeAssets.Linux but still keep SkiaSharp.NativeAssets.Linux.NoDependencies?

Both packages bring in the native binaries, so maybe it is getting confused...

I'll see if I can reproduce this if that still fails. Not sure why I haven't seen it.

**Comment by jaliyaudagedara** [comment]
Tried different combinations. Same issue :(

**Comment by jaliyaudagedara** [comment]
After spending hours, issue turned out to be this:

The artifact folder looks like this.

- **{artifact}\runtimes**

![image](https://user-images.githubusercontent.com/5653381/93462138-f2ca0780-f939-11ea-82f5-30585b1698ad.png)

It has different **libSkiaSharp.so** inside each linux-* folder. But for some reason, those aren't getting picked up.

Then I did this, basically copied  **libSkiaSharp.so** to the root folder. (linux-x64 in my case).
```
  <Target Name="CopyFilesAfterPublish" AfterTargets="_FunctionsPostPublish">
    <Copy SourceFiles="$(TargetDir)runtimes\linux-x64\native\libSkiaSharp.so" DestinationFolder="$(PublishDir)\bin\" />
  </Target>
```
![image](https://user-images.githubusercontent.com/5653381/93462403-64a25100-f93a-11ea-9ee9-5574d40129bc.png)

And everything seems to be working just fine.

**P.S:**

If getting the artifact from Build (rather than Publish),
```
  <Target Name="CopyFilesAfterPublish" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetDir)runtimes\linux-x64\native\libSkiaSharp.so" DestinationFolder="$(TargetDir)\bin\" />
  </Target>
```

**Comment by mattleibow** [comment]
But that is not what is supposed to be needed. The whole .NET Core things is to use the runtimes folder. That is the whole point of them.

I'll try repro this and see if it is maybe a bug in the publish step or the actual Azure Functions system. Might be that... They do have a slightly different system in the functions.

**Comment by jaliyaudagedara** [comment]
Exactly! It's supposed to be picking up necessary files based on the runtime. Thanks!

**Comment by emanuel-virca** [comment]
I am facing the same situation here. Any news on this?

**Comment by EngRajabi** [comment]
I still have this problem. I have installed the following packages

<PackageReference Include="SkiaSharp" Version="2.80.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />

**Comment by Gillibald** [comment]
You can either import the normal Linux package or the NoDependencies not both.

**Comment by EngRajabi** [comment]
I tested both modes. Single single and both.
``` c#
Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
```

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/5190#issuecomment-748332256

**Comment by EngRajabi** [comment]
How can I fix such a problem in Docker?

**Comment by YipingRuan** [comment]
> I still have this problem. I have installed the following packages
> 
> ```cs
> <PackageReference Include="SkiaSharp" Version="2.80.2" />
> <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.2" />
> <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />
> ```

This solved my issue  (2.80.3)

**Comment by swharden** [comment]
This also solved my issue, allowing Maui.Graphics tests to run on Linux in GitHub Actions 👍 🚀 

```xml
<PackageReference Include="Microsoft.Maui.Graphics" Version="6.0.101-preview.9.512" />
<PackageReference Include="Microsoft.Maui.Graphics.Skia" Version="6.0.101-preview.9.512" />
<PackageReference Include="SkiaSharp" Version="2.88.0-preview.145" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.0-preview.145" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.0-preview.145" />
```

Previously my error was:

```

System.TypeInitializationException : The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
----> System.DllNotFoundException : Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
Stack Trace:
 at Microsoft.Maui.Graphics.Skia.SkiaFontService.InitializeFontFamilies()
     ...
--DllNotFoundException
   at SkiaSharp.SkiaApi.sk_fontmgr_ref_default()
   at SkiaSharp.SKFontManager..cctor()
```

**Comment by venyowong** [comment]
> This also solved my issue, allowing Maui.Graphics tests to run on Linux in GitHub Actions 👍 🚀
> 
> ```
> <PackageReference Include="Microsoft.Maui.Graphics" Version="6.0.101-preview.9.512" />
> <PackageReference Include="Microsoft.Maui.Graphics.Skia" Version="6.0.101-preview.9.512" />
> <PackageReference Include="SkiaSharp" Version="2.88.0-preview.145" />
> <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.0-preview.145" />
> <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.0-preview.145" />
> ```
> 
> Previously my error was:
> 
> ```
> 
> System.TypeInitializationException : The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
> ----> System.DllNotFoundException : Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
> Stack Trace:
>  at Microsoft.Maui.Graphics.Skia.SkiaFontService.InitializeFontFamilies()
>      ...
> --DllNotFoundException
>    at SkiaSharp.SkiaApi.sk_fontmgr_ref_default()
>    at SkiaSharp.SKFontManager..cctor()
> ```

Thanks a lot! This is work for me.

**Comment by thanhtunng** [comment]
> This also solved my issue, allowing Maui.Graphics tests to run on Linux in GitHub Actions 👍 🚀
> 
> ```
> <PackageReference Include="Microsoft.Maui.Graphics" Version="6.0.101-preview.9.512" />
> <PackageReference Include="Microsoft.Maui.Graphics.Skia" Version="6.0.101-preview.9.512" />
> <PackageReference Include="SkiaSharp" Version="2.88.0-preview.145" />
> <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.0-preview.145" />
> <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.0-preview.145" />
> ```
> 
> Previously my error was:
> 
> ```
> 
> System.TypeInitializationException : The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
> ----> System.DllNotFoundException : Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
> Stack Trace:
>  at Microsoft.Maui.Graphics.Skia.SkiaFontService.InitializeFontFamilies()
>      ...
> --DllNotFoundException
>    at SkiaSharp.SkiaApi.sk_fontmgr_ref_default()
>    at SkiaSharp.SKFontManager..cctor()
> ```

Save my life! Worked on centos 7

**Comment by BenjaminMichaelis** [comment]
The Maui.Graphics didn't work for me (I am deploying on an linux azure function) but copying over the .so file did.
  ```
<Target Name="CopyFilesAfterPublish" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetDir)runtimes\linux-x64\native\libSkiaSharp.so" DestinationFolder="$(PublishDir)\bin\" />
  </Target>
```
I commented my fix here on [#622](https://github.com/Azure/Azure-Functions/issues/622) with this comment https://github.com/Azure/Azure-Functions/issues/622#issuecomment-1155320104

**Comment by petermisovic** [comment]
Hello, I have installed SkiaSharp version 2.88.0 + SkiaSharp.NativeAssets.Linux 2.88.0 + SkiaSharp.NativeAssets.Linux.NoDependencies 2.88.0 but I'm still having issue:

_System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception.
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory_

It does work on Windows machine, having issue in AWS on Linux. Please, what is the solution here?
Thank you!

**Comment by BenjaminMichaelis** [comment]
> Hello, I have installed SkiaSharp version 2.88.0 + SkiaSharp.NativeAssets.Linux 2.88.0 + SkiaSharp.NativeAssets.Linux.NoDependencies 2.88.0 but I'm still having issue:
> 
> 
> 
> _System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception.
> 
> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory_
> 
> 
> 
> It does work on Windows machine, having issue in AWS on Linux. Please, what is the solution here?
> 
> Thank you!

Have you tried what I did for azure on Linux as it may be a similar issue and fix? 

https://github.com/Azure/Azure-Functions/issues/622#issuecomment-1155320104

**Comment by marciosarabando** [comment]
Hi all,

Thanks, this forum helps to solve my problem.

I was having trouble using the lib QuestPDF running in a web api .net hosted in linux with the exception below:

 "System.DllNotFoundException: Unable to load shared library 'libHarfBuzzSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibHarfBuzzSharp: cannot open shared object file: No such file or directory"

In windows environments it's Ok, but to run on Linux I need to reference this package e insert the library **libSkiaSharp.so** manually in the project.

I managed to get the dll using this package "HarfBuzzSharp.NativeAssets.Linux" Version="2.8.2.1-preview.79"

![image](https://user-images.githubusercontent.com/17583192/176886845-31ff7747-b048-4993-9021-d3600c37f48f.png)

Thank you

**Comment by BenjaminMichaelis** [comment]
> The Maui.Graphics didn't work for me (I am deploying on an linux azure function) but copying over the .so file did.
> 
> ```
> <Target Name="CopyFilesAfterPublish" AfterTargets="PostBuildEvent">
>   <Copy SourceFiles="$(TargetDir)runtimes\linux-x64\native\libSkiaSharp.so" DestinationFolder="$(PublishDir)\bin\" />
> </Target>
> ```
> 
> I commented my fix here on [#622](https://github.com/Azure/Azure-Functions/issues/622) with this comment [Azure/Azure-Functions#622 (comment)](https://github.com/Azure/Azure-Functions/issues/622#issuecomment-1155320104)

Update on https://github.com/mono/SkiaSharp/issues/1341#issuecomment-1165595170.

A better fix because my previous solution in the comment linked above fails on an azure pipeline when running a publish command with the --no-build argument since that step doesn't grab onto the file that I was moving after build. So a better fix is this:

```csproj
<Target Name="CopyFilesAfterPublish" AfterTargets="AfterPublish">
  <Copy SourceFiles="$(TargetDir)runtimes/linux-x64/native/libSkiaSharp.so" DestinationFolder="$([System.IO.Path]::GetFullPath('$(PublishDir)'))/bin/" />
</Target>
```

I also use `$([System.IO.Path]::GetFullPath('$(PublishDir)'))` because if you look at how msbuild looks for this trigger, it uses the same syntax to get the full path instead of the relative path consistently. This has seemed to be the best fix even if using SkiaSharp.Linux.NoDependencies and works for both deploy directly to an azure function and via an azure pipeline.

I posted this same update here: https://github.com/Azure/Azure-Functions/issues/622#issuecomment-1172470499

**Comment by KirylKiryanchykau** [comment]
I had an issue with libHarfBuzzSharp.so when running on linux machine. Copying it to the ..runtime\linux64\native folder helped me

**Comment by mattleibow** [comment]
I think I need to find a way to detect this missing library on linux and give a slightly better exception to ask you to install the package.

**Comment by chin-udara** [comment]
I faced the aforementioned issue when deploying to a centos system.

For me it worked when I specified the runtime during the `dotnet publish` command and deployed the content of the `publish` folder inside the `<runtime>` folder. This folder included all the necessary `so` files.

Following was the publish command I used
`dotnet publish --configuration Release -r linux-x64`

The following folder included all the deps and nothing else needed to be done after deploying to the centos server.
`bin/Release/net6.0/linux-x64/publish`
