### ISSUE TITLE
[BUG]  Publishing ASP.NET MVC app copies native libraries to wrong folder

### ISSUE THREAD

**Issue by msmolka** [mono/SkiaSharp#1413]
**Description**
Publishing ASP.NET MVC app copies native libraries to wrong folder.
Previous version 1.63 worked properly.
**Code**
Just Publish ASP.NET MVC app

**Expected Behavior**

native dlls are copied to bin folder

**Actual Behavior**

native dlls are copied to bin and root folder:

**Basic Information**

- Version with issue:  2.80.1
- Last known good version:  1.63.3
- IDE:  Visual Studio 2019
- Platform Target Frameworks: .NET 4.7.2

**Screenshots**

![obraz](https://user-images.githubusercontent.com/6661461/87679376-63a74480-c77c-11ea-97f5-d6e37a70bb8e.png)

**Comment by mattleibow** [comment]
This is the new functionality to support Any CPU - the native binaries are in the x86/x64/arm folders. The library will now look in there first to try and find the correct library. 

Previously, the file copied to the root of the bin directly would be wrong in the CPU was different on the target machine. To avoid the numerous crashes and issues, we no longer copy the possibly incorrect binary. The reason the macOS (dylib) binary is there is because it is a "fat" binary with all the architectures in one.

**Comment by msmolka** [comment]
But files are still copied to bin/x86 bin/x64 etc. SkiaSharp.dll is in bin folder. In bin folder are native dlls in respective folders. BUT additionally the same in web app root.

**Comment by msmolka** [comment]
Also removing these folders from root does not any harm, because dll from bin/x64 is used not from root x64

**Comment by mattleibow** [comment]
> because dll from bin/x64 is used not from root x64

It is now in v2.x. No longer looking in the root due to Windows having issues when running in a 32-bit process but building on a 64-bit machine. VS would always copy the wrong file.
