### ISSUE TITLE
Classes should not dispose objects that they didn't create

### ISSUE THREAD

**Issue by MhAllan** [mono/SkiaSharp#1430]
I want to create helper methods that wrap some functionalities like this one for example

```chsharp
public bool IsImage(Stream stream) => SKCodec.Create(stream) != null;
```

The problem is that it created SKCodec and it is disposable, so we have to dispose it, but if we do like this

```csharp
public bool IsImage(Stream stream) 
{
    using(var codec = SKCodec.Create(stream))
    {
        return codec != null;
    }
}
```
It will also dispose the stream, and I obviously don't want to dispose the stream.

So I ended up returning Disposable wrapper or the SKCodec itself, so the client can dispose it when done with the stream. which makes my helper methods very useless wrappers that encapsulate nothing.

I think an object shouldn't dispose a resource that it doesn't own, if the Stream is passed to SKCodec, SKCodec should not dispose it because the client could be still using it.

**Comment by mattleibow** [comment]
Unfortunately, `SKCodec` always takes ownership of the stream and will close it. I don't particularly agree with this decision, but it is the one Google went with.
This is documented: https://docs.microsoft.com/dotnet/api/skiasharp.skcodec.create

However, since determining if it is a valid image only requires the first few bytes. You can copy those into a temporary stream and use that: `SKCodec.MinBufferedBytesNeeded`.
Another thing that you can do (and might be better if you want to actually do other things) is create a proxy stream that the codec uses. Then it can close whatever it wants, but your stream still works. There is actually just such a type in SkiaSharp already: `SKFrontBufferedManagedStream`.

I can't switch that to be the default now as it is a breaking change, but you can do that in your code.

**Comment by mattleibow** [comment]
I'll leave this issue open so I can maybe add an overload to do this - the default will be to always close, but there is an option to not.

**Comment by MhAllan** [comment]
A proxy stream is great suggestion, Thank you so much @mattleibow

**Comment by mattleibow** [comment]
One thing to keep in mind is that the stream position will move. This may be unexpected. As the stream is read, the cursor moves. So a double call to IsImage will fail the second time.

I wonder if resetting the stream position is worth it? Or leave it up to the dev?

**Comment by MhAllan** [comment]
First, you are such a quality developer I really admire how you think of everything when answering a question. 

I have just added the position seeking seconds before reading your answer. my opinion is that, methods shouldn't alter the state of objects passed to them because they don't own them. so yes, the IsImage wrapper have to set the position back. If methods alter states of objects passed to them it makes programming hard and messy and you will be stressed whenever you call a method from any library.

```csharp
public static bool IsImage(Stream stream)
        {
            if (stream == null)
                throw new ArgumentNullException(nameof(stream));

            using (var skStream = new SKFrontBufferedManagedStream(stream, SKCodec.MinBufferedBytesNeeded))
            {
                var position = stream.Position;
                try
                {
                    var codec = SKCodec.Create(skStream);
                    var result = codec != null;
                    if (codec != null)
                        codec.Dispose();

                    return result;
                }
                finally
                {
                    stream.Seek(position, SeekOrigin.Begin);
                }
            }
        }
```

**Comment by mattleibow** [comment]
Just thought of something. You are setting the position to 0, but what happens if this is some zip stream where the position is at an offset in reality.

The other part is slightly different in that some streams can't seek because of what they are. For example, an http stream is forward only.

Not sure what the best solution for this is. Might have to just leave it up to the dev to do it because no matter what we do, it can't go back.

**Comment by MhAllan** [comment]
"Unseekable" streams can't make use of such a tool in all cases this `IsImage` needs stream to be able to seek to work and keeps the streams available. zip stream is a good point. so yes, the position should be handled by the dev, Agree.
