### ISSUE TITLE
[BUG] Polygon not being filled in

### ISSUE THREAD

**Issue by sremiger1** [mono/SkiaSharp#1446]
**Description**

I want to fill in a polygon for charting, but it will not fill in.  I was able to fill in a rectangle for comparison.  Below is the sample code.
This is simplified, I actually found this using the shader property of SKPaint. 

**Code**

```
SKImage image = null;
using (var surface = SKSurface.Create(new SKImageInfo(867, 220)))
{ 
	SKCanvas canvas = surface.Canvas;
	canvas.Clear(new SKColor(Color.Transparent.R, Color.Transparent.G, Color.Transparent.B));
	string s = "5,210 5,102.62 289,183.81 838.1,68.57 838.1,210 5,210";
	var points = s.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries)
		.Select(x => {
			string[] p = x.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
			return new SKPoint(Convert.ToSingle(p[0].Trim()), Convert.ToSingle(p[1].Trim()));
		}).ToArray();

	var polygonPaint = new SKPaint()
	{
		Color = SKColors.Red,
		Style = SKPaintStyle.StrokeAndFill,
		IsAntialias = true,
		StrokeJoin = SKStrokeJoin.Round
	};
	SKRect r = new SKRect(50, 50, 100, 100);
	canvas.DrawRect(r, polygonPaint);
	canvas.DrawPoints(SKPointMode.Polygon, points, polygonPaint);
	image = surface.Snapshot();
}
return image;
```

**Expected Behavior**
I would expect the polygon to fill in, it is closed the same way as the rectangle.

**Actual Behavior**
The rectangle is filling in and the polygon is not filling

**Basic Information**
- Version with issue:  2.80.1
- IDE:  Visual Studio 2019
- Platform Target Frameworks: 
  - Windows Classic:  Windows 10

**Screenshots**

![image](https://user-images.githubusercontent.com/26170868/89415118-0d7d4f80-d6f1-11ea-94d4-f3fbba6e1c46.png)

**Comment by mattleibow** [comment]
This is quite interesting. I asked the folks on the engine now, so we shall see what they say: https://groups.google.com/g/skia-discuss/c/fB270mBYtkk

However, in the meantime, there might be a better way to do this by using `SKPath`. In fact, the first way is just a matter of converting the points string into a `SKPath` using `ParseSvgPathData`. This will not work with your string because it is missing the very first "move" operation, but this is very easy to do by literally just adding a "M " to the string and can also be done at runtime just fine:

```csharp
// add an "M" to the start and parse
var s = "M 5,210 5,102.62 289,183.81 838.1,68.57 838.1,210 5,210";
using var path = SKPath.ParseSvgPathData(s);
```

If this is not possible, then you can also get a path from the points array:

```csharp
var path = new SKPath();
path.AddPoly(points);
```

In both cases, you can now just draw the path like you would any other shape:

```csharp
canvas.DrawPath(path, polygonPaint);
```

**Comment by scottremigeraccuweather** [comment]
Yes, that is exactly what I tried and it did work.  Also, I do not agree with Mike's response, A Polygon by [definition](https://www.dictionary.com/browse/polygon?s=t) Is a closed object and should behave no differently than a rectangle.  That is why they are used in SVG.

thanks for the help.

**Comment by sremiger1** [comment]
That is exactly what I converted to and it did work.  I however do not agree with Mike's response By [definition](https://www.dictionary.com/browse/polygon?s=t) a polygon is a closed object and therefore should behave the exact same way a rectangle should behave.

Thanks for the help.

**Comment by mattleibow** [comment]
Just a note for the future: Draw points always draws lines and not fill.
