### ISSUE TITLE
Skia.Forms.Demo.Droid V1.54.0 Build Error

### ISSUE THREAD

**Issue by hanslerhans** [mono/SkiaSharp#146]
Hi all,

I receive following build errors for the Android sample (V1.54.0):

"Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.	Skia.Forms.Demo.Droid	\SkiaSharp-1.54.0\samples\Skia.Forms.Demo\Droid\Resources\values\styles.xml	2	Build "

"No resource found that matches the given name: attr 'colorPrimaryDark'.	Skia.Forms.Demo.Droid	D:\011_Dev\sfa\SkiaSharp-1.54.0\samples\Skia.Forms.Demo\Droid\Resources\values\styles.xml	2	Build"

The same applies for "windowActionBar", "windowNoTitle", etc.; The other projects (iOS and UWP) are working fine. I'm sure there is a simple reason for that, which I can't figure out at the moment. I'm using Visual Studio Community 2015. 

By the way, you are doing a great job with this project! Can't wait to get this thing running and messing around with it! ;)

**Comment by mattleibow** [comment]
Hi @hanslerhans this is not a bug directly related to SkiaSharp, but rather your current setup with the Google build tools. Make sure that you have the latest (or rather for now, matching) of everything.

If you are using the v24 build tools, then you have to make use of the v24 AppCompat library and the v24 platform tools. However, in this case Xamarin.Forms is not yet updated to use v24, so everything has to be at v23. Right now I am waiting on Xamarin.Forms for an update which uses v24 so that I can update my build tools to v24 :(

The solution for now, uninstall the v24 build tools and make sure that everything is at v23 until Xamarin.Forms gets an update. 

Also, I would strongly suggest asking on https://gitter.im/xamarin/Xamarin.Forms. That is where the real Xamarin.Forms experts live and chat.
