### ISSUE TITLE
[BUG] Exception on iOS after upgrade

### ISSUE THREAD

**Issue by omghb** [mono/SkiaSharp#1463]
**Description**

After upgrading SkiaSharp.Views.Forms from 1.68.3 to 2.80.1 I get the following exceptions:

```
System.EntryPointNotFoundException
  Message=sk_version_get_milestone assembly:<unknown assembly> type:<unknown type> member:(null)

System.InvalidOperationException
  Message=The version of the native libSkiaSharp library is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [80.0, 81.0).

System.TypeInitializationException
  Message=The type initializer for 'SkiaSharp.SKObject' threw an exception.
```

**Basic Information**

- Version with issue:  SkiaSharp.Views.Forms 2.80.1
- Last known good version:  1.68.3
- IDE:  Visual Studio and Visual Studio for Mac
- Platform Target Frameworks:
  - Xamarin.Forms: 4.7.0.1260
  - Xamarin.Essentials: 1.5.3.2
  - Xcode: 11.5
  - iOS: 13.5
- Target Devices: 
  - iPad Gen7 Simulator iOS 13.5

**Comment by mattleibow** [comment]
This is very interesting.

Are the same versions of SkiaSharp installed into the core project as well as the iOS project? Also, can you try a rebuild?

This is basically a manifestation of a bug in some part of Xamarin.iOS where it wasn't copying the new binaries to the device. However, this was fixed in v2, but the first run needs a rebuild - or even an uninstall of the app on the device.

However, after uninstalling the app and doing a rebuild, all future updates should not have this issue.

**Comment by omghb** [comment]
My issue was that the iOS project did not have a reference to SkiaSharp. The old version worked without it. After adding the reference it works now.

Thanks for the help.

**Comment by mattleibow** [comment]
Thanks for the feedback. The next update to SkiaSharp will make it work without a direct reference.
