### ISSUE TITLE
[QUESTION]  Another Access Violation error - "Attempted to read or write protected memory""

### ISSUE THREAD

**Issue by Stuart88** [mono/SkiaSharp#1477]
Hi, I know this issue has been dealt with before, but in those cases the solution was relating to using (or not using) async/await operations. In my case, there is no async/await, so I'm not sure where to start to get this working.

The code is designed to grab an image resource, change the colour of the image, then return the re-coloured image as an ImageSource. It has never crashed on Android, but regularly occurs when running in UWP.

I know I'm doing something wrong because sometimes the images are returned looking like fuzzy white noise, so obviously the resource is being created from the wrong memory. Sadly my knowledge stops there. I don't know which area I'm getting wrong here; any advice would be appreciated. 

Thanks!

The error is always thrown on the last line.

``` c#
 public static ImageSource TintableIconImageFromSource(string source, Assembly assembly)
        {
            string resourceId = $"XamarinFormsGISmapp.Images.Icons.{source}";

            SKBitmap resourceBitmap;

            using (Stream stream = assembly.GetManifestResourceStream(resourceId))
            {
                resourceBitmap = SKBitmap.Decode(stream);
            }

            SKImageInfo info = new SKImageInfo(resourceBitmap.Height, resourceBitmap.Width);
            SKSurface surface = SKSurface.Create(info);
            SKCanvas canvas = surface.Canvas;

            using (SKPaint paint = new SKPaint())
            {
                paint.ColorFilter = ColourFilterMatrix(R, G, B, alpha);

                canvas.DrawBitmap(resourceBitmap, info.Rect, paint);
            }

            SKImage image = SKImage.FromPixels(surface.PeekPixels());

            return ImageSource.FromStream(() => image.Encode().AsStream());
        }
```

**Comment by mattleibow** [comment]
You are _almost_ there with the code.

The issue is that `surface.PeekPixels()` returns a non-referencing pointer to the raw pixel data. What is happening, you now have the pointer to the surface pixels, and then you are creating a new image around those pixels - without copying. So, all the image knows is that there is pixel data at a memory location. As far as the surface knows, no one is referencing it.

To fix this, there are 2 ways, one involves copying and the other is actually less copying.

**Option A**

Copy the pixel data when creating the image using `SKImage.FromPixelCopy`.

```csharp
SKImage image = SKImage.FromPixelCopy(surface.PeekPixels());
```

**Option B (i)**

Don't copy anything out of the surface at all. Get the pixels and then encode directly.

```csharp
SKImageInfo info = new SKImageInfo(resourceBitmap.Height, resourceBitmap.Width);
SKSurface surface = SKSurface.Create(info);

// ... draw ...

return ImageSource.FromStream(() => surface.PeekPixels().Encode(SKEncodedImageFormat.Png, 100).AsStream());
```

**Option B (ii)**

Another way is that you can actually use the _encoded_ data in the construction of the `ImageSource`.

This might be the best option because all the work is being done in the main method, and all the actual `ImageSource` does is read the stream. 

```csharp
SKImageInfo info = new SKImageInfo(resourceBitmap.Height, resourceBitmap.Width);
SKSurface surface = SKSurface.Create(info);

// ... draw ...

// get the data here
SKData data = surface.PeekPixels().Encode(SKEncodedImageFormat.Png, 100);

return ImageSource.FromStream(() => data.AsStream());
```

**Option B (iii)**

But, since the actual work inside `ImageSource.FromStream` is done on a background thread, it may be work making the entire operation in that callback.

> NOTE: one thing to check to see if the `ImageSource` actually caches this result if you have multiple images on screen - ie: this object is reused.

```csharp
public static ImageSource TintableIconImageFromSource(string source, Assembly assembly)
{
	return ImageSource.FromStream(() =>
	{
		var resourceId = $"XamarinFormsGISmapp.Images.Icons.{source}";

		using var stream = assembly.GetManifestResourceStream(resourceId);
		var resourceBitmap = SKBitmap.Decode(stream);

		var info = new SKImageInfo(resourceBitmap.Height, resourceBitmap.Width);
		using var surface = SKSurface.Create(info);
		using var canvas = surface.Canvas;

		using var paint = new SKPaint();
		paint.ColorFilter = ColourFilterMatrix(R, G, B, alpha);
		canvas.DrawBitmap(resourceBitmap, info.Rect, paint);

		using var pixmap = surface.PeekPixels();

		var data = pixmap.Encode(SKEncodedImageFormat.Png, 100);
		return data.AsStream();
	});
}
```

**Comment by Stuart88** [comment]
Thanks!

I went for B(iii)
