### ISSUE TITLE
[BUG] SKShader.CreatePicture not working properly with SKPaint.Reset and SKPath.Reset

### ISSUE THREAD

**Issue by wieslawsoltes** [mono/SkiaSharp#1500]
**Description**

SKShader.CreatePicture not working with SKPaint.Reset and SKPath.Reset

**Code**

https://gist.github.com/wieslawsoltes/08a9b739fb3df25e191f9e99b943a7c5

For reference code without Reset() calls, using new instances.
https://gist.github.com/wieslawsoltes/c615e2dccf7fc9ce86f7ef5c8153cafb

**Expected Behavior**

![AvaloniaSample_2020-09-15_21-03-42](https://user-images.githubusercontent.com/2297442/93254289-6b915e00-f798-11ea-8cc6-bc5a7bc0f6f8.png)

**Actual Behavior**

![AvaloniaSample_2020-09-15_21-04-59](https://user-images.githubusercontent.com/2297442/93254298-70eea880-f798-11ea-9319-1d7caee756c8.png)

**Basic Information**

- Version with issue:  2.80.2
- Last known good version:  
- IDE:  Visual Studio / Visual Studio Code
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by mattleibow** [comment]
@wieslawsoltes does anything different happen when you don't reset the path? Does having _just_ the paint reset also stop working?
I originally added the reset for the paint after a request, and I never got any negative feedback from it.

A `SKPaint` reset is literally creating a new pain instance in the exact same place: https://github.com/google/skia/blob/master/src/core/SkPaint.cpp#L96
And, when it is passed around, I believe it is copied. However, a picture may be using a reference.

Could you confirm that it is both the paint AND the path having issues, or maybe it is one and the other is just causing it?

**Comment by wieslawsoltes** [comment]
Both have issue when used separately and together. I was under impression that Reset() does not allocate new objects?

**Comment by mattleibow** [comment]
It does not in C# and the C++ side is interesting. It technically creates a new object over the old one. So not really a new object, just "re-initializes" it.

**Comment by wieslawsoltes** [comment]
This pointer constructor magic.

**Comment by mattleibow** [comment]
@wieslawsoltes  I have been looking at this and I think there might be a few things going on here.

First, I need to check some more, but I don't think you can reset the paths. This might be held by reference when drawing, so that is why the top part of the picture - the bit made up of the small path blocks - is reset.

The other part is where it appears a font size is being set, then reset and then drawn.

Over here, the paint is set:
https://gist.github.com/wieslawsoltes/08a9b739fb3df25e191f9e99b943a7c5#file-pservers-pattern-01-b-svg-cs-L90

Then reset over here:
https://gist.github.com/wieslawsoltes/08a9b739fb3df25e191f9e99b943a7c5#file-pservers-pattern-01-b-svg-cs-L134

Then drawn here:
https://gist.github.com/wieslawsoltes/08a9b739fb3df25e191f9e99b943a7c5#file-pservers-pattern-01-b-svg-cs-L159

Even though you are referencing the old paint object _variable_ you have actually reset it twice since.

This might be a result of a container setting some properties and then the elements changing them? You may need to investigate some sort of stack-based paint collection. I think it might be possible to have multiple paint objects at the same time due to the hierarchical nature of the xml.
