### ISSUE TITLE
[FEATURE] Add a .NET Interactive kernel extension to display SkiaSharp types in notebooks

### ISSUE THREAD

**Issue by bmitc** [mono/SkiaSharp#1581]
**Is your feature request related to a problem? Please describe.**

I would like to be able to learn, experiment, use, document, and more with SkiaSharp in a .NET Interactive notebook. This means that in using SkiaSharp, various types could be displayed in the output cells of a notebook. I think this would be a huge feature and encourage more people to use SkiaSharp. It would open up a lot of use cases that don't necessarily require embedding SkiaSharp into a window or app or use cases that are better served in a notebook.

**Describe the solution you'd like**

It would be great to simply have .NET Interactive display images and animations created by SkiaSharp. For example:

![](https://user-images.githubusercontent.com/65685447/99871019-fc235a80-2b9c-11eb-9715-a5714afec344.png)

**Describe alternatives you've considered**

n/a

**Additional context**

I had previously created an [issue in the .NET Interactive repository](https://github.com/dotnet/interactive/issues/902) with some more details. The way it was explained and that I understand it is that SkiaSharp would need to add a .NET Interactive kernel extension with implementations for each base type that would need to be displayed in an output cell.

* [sample extensions](https://github.com/dotnet/interactive/tree/main/samples/extensions)
* [extending .NET Interactive](https://github.com/dotnet/interactive/blob/main/docs/extending-dotnet-interactive.md)

**Comment by bmitc** [comment]
With some help and guidance, I'd be willing to help implement this. Although, I mainly know F# and haven't written C# code.

**Comment by jonsequitur** [comment]
@bmitc The formatter can be written in F#. We're putting together a sample that will walk you through how to do it.

**Comment by mattleibow** [comment]
This looks really cool. The main thing that might cause issues is the native component. SkiaSharp is just a wrapper. Are the native dll/dylib/so files loaded automatically?

**Comment by jonsequitur** [comment]
Yes. It seems to work just fine in the notebook.

**Comment by mattleibow** [comment]
![image](https://user-images.githubusercontent.com/1096616/120077576-543a9c80-c0ab-11eb-8212-3e9f52cb936f.png)

**Comment by mattleibow** [comment]
![image](https://user-images.githubusercontent.com/1096616/120078157-594d1b00-c0ae-11eb-9fc3-4c6a01e590db.png)

**Comment by mattleibow** [comment]
@bmitc thanks for raising this issue. I somehow missed this whole announcement... I have been so heads down with MAUI I lost track of everything. However, when playing around with this, I accidentally created the extension. Literally like 20 lines of code. I did not expect that 😂

However, my PR #1710 is just the bare bones.

I did not mean to do this so quickly, especially since you did volunteer. Sorry about that, however, there is still a bit more work needed a the general display work is pretty minimal to say the least. It would still be a really good to actually write better "renderers" and maybe have more info or even some interactivity. 

Right now it just blats the image to the screen, but this is not so good because huge images will just fill the screen. There probably should be a resizing mechanism and maybe a click-to-see-full-size as well as other pertinent info - like bounds, color type and more.

If this still sounds interesting to you, then I would totally accept PRs on this.

**Comment by jonsequitur** [comment]
We spent some time working on this the other day just to understand the problem a bit. I think ideally, the formatter should be able to return multiple representations in different MIME types, e.g. `image/png` and `text/html`. I'm also curious as to whether  some portions of the implementation would be reusable enough that they should go into [Microsoft.DotNet.Interactive.Formatting](https://www.nuget.org/packages/Microsoft.DotNet.Interactive.Formatting/) so that similar extensions for other image libraries can make use of them.

Related: https://github.com/dotnet/interactive/issues/1374

@lytesfazion @cerasamson @AngleQian @colombod
