### ISSUE TITLE
Problems with the latest SkiaSharp.Views Nugets

### ISSUE THREAD

**Issue by jazzay** [mono/SkiaSharp#161]
Hi @mattleibow , I'm really excited to try the new views stuff. Unfortunately when I try to load up the FormsSample on windows with my iOS device connected it fails to restore the iOS portions of the nuget properly. There exists no MonoTouch10 or Xamarin.iOS10 lib folders like there are for Xamarin.Forms.2.3.0.49. Perhaps your Nuspec has a problem? 

Here's a screenshot of the package contents:

![image](https://cloud.githubusercontent.com/assets/554363/19336088/5b9cabda-90bd-11e6-8354-fe28dbd8e928.png)

Where's Xamarin.Forms looks like this:

![image](https://cloud.githubusercontent.com/assets/554363/19336104/8931fbea-90bd-11e6-994c-ff60765addef.png)

**Comment by jazzay** [comment]
I noticed that in the Xamarin.Forms nuspec it references:
    <group targetFramework="Xamarin.iOS10"> and  <file ... target="lib\Xamarin.iOS10" />

Where as SkiaView references:
    <file .... target="lib/XamariniOS" />

**Comment by mattleibow** [comment]
Thanks for reporting the issue. I am closing this as we have "resolved" it. The problem was the fact that when building the code from the repo, the NuGets are installed from the output directory. This installation results in the build being cached in the NuGet cache.

To resolve, delete these folders:

    C:\Users\<username>\.nuget\packages\SkiaSharp\
    C:\Users\<username>\.nuget\packages\SkiaSharp.Views\
    C:\Users\<username>\.nuget\packages\SkiaSharp.Views.Forms\

This will force a download from nuget.org

**Comment by jazzay** [comment]
That worked. Thanks @mattleibow !
