### ISSUE TITLE
BadImageFormatException when build target is x64

### ISSUE THREAD

**Issue by BartStodola** [mono/SkiaSharp#1641]
Can anybody explain to me please, why I run into a **BadImageFormatException** when I use latest SkiaSharp from Nuget in a WPF Application that was build with target:_x64_?
Is there any _x86_ dependency inside SkiaSharp?
If the Target is _AnyCpu_ no issue! But unfortunatelly I can not change back to _AnyCpu_!

**Comment by BartStodola** [comment]
Application::An unhandled exception just occurred: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception
this is exactly the exception I get.

**Comment by mattleibow** [comment]
I am assuming this is with the classic .NET Framework?

What version of SkiaSharp are you running?

**Comment by BartStodola** [comment]
Yes, target platform is .NetFramework
Versions via Nuget:
SkiaSharp 1.68.3
SkiaSharp.Views.WPF 1.68.3

**Comment by mattleibow** [comment]
Are you able to test with the much later v2.80.2? I think this was originally an issue but was fixed by not relying on the automatic detection of the platform. 

Check to see if Prefer 32-bit is checked or not. Also make sure that the libSkiaSharp.dll exists next to the SkiaSharp.dll in the app output directory.

**Comment by BartStodola** [comment]
Latest Version v2.80.2 fixed this Issue.
