### ISSUE TITLE
[BUG] The new packing mechanism for special packages is not packing the lipo'ed files

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#1682]
**Description**

For example, the libHarfBuzzSharp.a in the root of iOS and the libSkiaSharp.dylib for macOS.

**Comment by mattleibow** [comment]
But I notice the iOS framework is there...

**Comment by tmijieux** [comment]
just this weekend i tried to build the complete nuget (boostrapper.ps1 with -packall -buildall options) on windows,
using downloaded (--skipExternals=all) native bits, but there were no "lipo ed" files from the externals-download, instead there was a folder for each architecture, maybe this is related ...

I had to do some little local modifications in order to successfully build a nuget:
https://github.com/tmijieux/SkiaSharp/commit/7da746b4a907fe3172077d87235121c8ca8c2cc8

**Comment by mattleibow** [comment]
Yeah, I think I mad a mistake somewhere. Bit of a bummer.

**Comment by mattleibow** [comment]
Should be fixed soon.
