### ISSUE TITLE
[BUG] Unable to run Skia.Gtk/Skia.Wpf Uno Application with SkiaSharp.Views.Uno reference.

### ISSUE THREAD

**Issue by vkotov** [mono/SkiaSharp#1688]
### Description

When I create new project for Uno platform with **Uno Platform Solution Templates** and add reference to SkiaSharp.Views.Uno (latest stable 2.80.2) the build is successful, but with follow warnings:

**TestApplication.Skia.Gtk**
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework **'net5.0'**. This package may not be fully compatible with your project.	

**TestApplication.Skia.Wpf.Host**
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework **'.NETCoreApp,Version=v3.1'**. This package may not be fully compatible with your project.	

But when I try to start application it crashes with runtime error: **FileNotFoundException: Could not load file or assembly 'Uno.UI.Wasm, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.**
 
### Expected Behavior

Solution should be compiled without specified warnings and all applications should executed without initialization errors.

**Actual Behavior**

Unable to run Gtk and Wpf projects without errors after solution creation from scratch.

**Basic Information**

- Version with issue:  2.80.2
- Last known good version:  none
- IDE:  Visual Studio
- Platform Target Frameworks: Uno.UI 3.6.6
  - Linux:  Ubuntu 20.04 
  - Windows Classic:  Windows 7

**Comment by ElanHasson** [comment]
I'm seeing the same thing using `dotnet new unoapp-winui -o MyApp -v true`

**Comment by mattleibow** [comment]
Is this still an issue. Currently the SkiaSharp.Views package does not support net5.0 because it depends on very old gtk2 things. The correct package that should have been used is SkiaSharp.Views.WPF.

I believe this is now changed in Uno, however, this can be worked around by adding a reference to SkiaSharp.Views and then adding a `NoWarn="NU1701"` to the item.

`<PackageReference Include="SkiaSharp.Views" NoWarn="NU1701" />`

I will close this because I believe this was fixed. However, if it is still the case, please open an issue in the Uno repo as they should not be using this package.
