### ISSUE TITLE
Source file '\Binding\SkiaSharp.Portable\SkiaPortable.cs' could not be found.

### ISSUE THREAD

**Issue by Goldstrike** [mono/SkiaSharp#171]
Hello, 
Il tried to test the 'SkiaSharpSource.Windows' solution but I can't build: I get an error saying that the class 'SkiaPortable.cs' is missing. Is it normal?

**Comment by mattleibow** [comment]
Hi @Goldstrike. this is expected because that file is generated from the binding projects.

In order to generate that file, you need to run this build target:

    .\bootstrapper.ps1 -Target externals-genapi

That will create the file. In order to build so that you can actually run the tests or platform libraries, you will need to first build the native library and managed wrappers:

    .\bootstrapper.ps1 -Target libs
