### ISSUE TITLE
[QUESTION] System.IO.FileNotFoundExcption : Could not load file or assembly 'gtk-sharp

### ISSUE THREAD

**Issue by ibocon** [mono/SkiaSharp#1780]
I am trying to test view in nunit test project.
View uses **SkiaSharp.Views.Forms.SKCanvasView** internally. Therefore, I include **SkiaSharp.Views.Forms.GTK** as NuGet Dependencies like below. (#1225)

![image](https://user-images.githubusercontent.com/9730869/130028056-4817833f-7cfb-4805-9873-2d1c23c2ab1a.png)
![image](https://user-images.githubusercontent.com/9730869/130028489-f7a63ffa-a391-49a9-b9a3-102afcadec5d.png)

But after build I am getting following exception,

![image](https://user-images.githubusercontent.com/9730869/130028677-7161c4fe-2ef3-4383-844b-988a3105a021.png)

Is there a way to solve this?

I can find **gtk-sharp.dll** in _/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/gac/gtk-sharp/2.12.0.0__35e10195dab3c99f_ folder.
I tried install GTK# (https://www.mono-project.com/docs/gui/gtksharp/).

#### Package Console
```
Package 'OpenTK 3.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Package 'OpenTK.GLControl 3.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Package 'SkiaSharp.Views.Forms.GTK 2.80.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Package 'Xamarin.Forms.Platform.GTK 5.0.0.2012' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```
However **OpenTK 3.0.1** does not depends on .NET Framework. Why it is restoring using .NET Framework?

![image](https://user-images.githubusercontent.com/9730869/130035863-ded5f1b3-52f6-476a-bfda-a5669935957d.png)

**Comment by mattleibow** [comment]
There are a few things that might cause issues. You are building with Xamarin.Forms and using GTK, so I am not sure why the build is not finding the gtk-sharp.dll from the GAC. However, this might be because it is a .NET Core/.NET Standard test library? In this case, the GAC is not used.

You can add the GAC to the lookup in your csproj by adding this:

```xml
  <PropertyGroup>
    <!--
      SDK-style projects cannot reference GAC assemblies: 
      https://github.com/dotnet/sdk/issues/987
    -->
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>
```

However, you may actually want to download and include the gtk-sharp bits into the app so you don't have to install gtk on client machines. But, if this is a dev/testing thing, then you might be fine.

The case with OpenTK restoring to .NET Framework, this is because it is only including the bits for that. The NuGet.org info shows nothing because the package author did not specify anything under the dependencies. However, if you have a look at the package explorer, you can see the lib folder only has net20: https://nuget.info/packages/OpenTK/3.0.1

If you don't like the warning, you can just ignore it:

```xml
<PackageReference Include="OpenTK" Version="3.0.1" NoWarn="NU1701" />
```

Or, you can update go a later version that is .NET Standard based.
