### ISSUE TITLE
System.DllNotFoundException Impossible to load DLL libSkiaSharp[BUG] 

### ISSUE THREAD

**Issue by julientrflz** [mono/SkiaSharp#1791]
Hello,
I am using VS2019 .NET Framework 4.7.2. I have through nuget package install `Oxyplot.SkiaSharp.Wpf` 2.1.0-Preview1 which download me `Oxyplot.SkiaSharp` 2.1.0-Preview1, `HarfBuzzSharp` 2.6.1.4, `SkiaSharp` 1.68.3, `SkiaSharp.HarfBuzz` 1.68.3, `SkiaSharp.Viewq.Desktop.Common` 1.68.3, `System.Buffer` 4.4.0, `System.Memory` 4.5.3 and `System.Runtime.CompilerServices.Unsafe` 4.5.2

Once I used on my XAML Oxyplot.SkiaSharp.Wpf, I have a exception thrown. 

XAML:
```
`<Window
    x:Class="OxyPlot.Development.Rostov.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:OxyPlot.Development.Rostov"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:oxySkia="clr-namespace:OxyPlot.SkiaSharp.Wpf;assembly=OxyPlot.SkiaSharp.Wpf" 
    xmlns:oxy="http://oxyplot.org/wpf"
    Title="MainWindow"
    Width="800"
    Height="450"
    d:DataContext="{d:DesignInstance Type=local:MainWindow,
                                     IsDesignTimeCreatable=False}"
    DataContext="{Binding RelativeSource={RelativeSource Self}, Mode=OneTime}"
    mc:Ignorable="d">
    <Grid>
        <oxySkia:PlotView
            Grid.Row="0"
            Grid.Column="0"
            MinWidth="100"
            MinHeight="100"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Stretch"
            Model="{Binding Path=DataWeather.PlotModelData, Mode=OneWay}" 
    </Grid>
</Window>/>`
```

Design view :
```
`System.DllNotFoundException
Impossible de charger la DLL 'libSkiaSharp': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
   à SkiaSharp.SkiaApi.sk_colorspace_new_srgb()
   à SkiaSharp.SKColorSpace..cctor()

System.TypeInitializationException
Une exception a été levée par l'initialiseur de type pour 'SkiaSharp.SKColorSpace'.
   à SkiaSharp.SKColorSpace.EnsureStaticInstanceAreInitialized()
   à SkiaSharp.SKObject..cctor()

System.TypeInitializationException
Une exception a été levée par l'initialiseur de type pour 'SkiaSharp.SKObject'.
   à SkiaSharp.SKObject.get_Handle()
   à SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   à SkiaSharp.SKPaint.Dispose(Boolean disposing)
   à SkiaSharp.SKNativeObject.Finalize()`
```

I don't know what I have to do in order to get it right. I have tried on a .NETCORE wpf application and it worked, but not in the .NET FRAMEWORK...

**Comment by mattleibow** [comment]
Are you able to attach a sample?

Also, you can try setting the property `<PreferredNativeSkiaSharp>` to either `x64` or `x86`. It might be the case that the build system is selecting the wrong native library. The reason .NET Core works is because it makes sure the right one is laoded.

This is quite an old version of skia, and quite a few bugs with selecting the correct dll have been fixed. You could also try updating SkiaSharp to a v2.x.

**Comment by nngw-ep** [comment]
Had the same problem, but only when using Package Reference instead of packages.config.
When using the VS migration option to Package References, it marks HarfBuzzSharp and SkiaSharp as 'top level' packages and, of course, has some more transitive dependencies. It adds those two together with OxyPlot.SkiaSharp.Wpf as Package Reference and I got all the native libs.

**Comment by mattleibow** [comment]
This seems to be resolved?
