### ISSUE TITLE
[BUG] Skia draws variable fonts with incorrect width and weight

### ISSUE THREAD

**Issue by Moskvinr** [mono/SkiaSharp#1795]
For example, this Vast Variable Font has default values of **width = 50** and **weight = 400**. But Skia draws with **width = 5** (even if min value is 50) and **weight = 100**

![image](https://user-images.githubusercontent.com/22072836/132017701-9073c7f3-6699-486d-afd9-2c8dd6d63d8e.png)

**Comment by mattleibow** [comment]
This may be because by default Skia does not really do anything fancy with text. You can try making use of SkiaSharp.HarfBuzz and then draw text with `DrawShapedText`.

However, I would strongly recommend using RichTextKit as that is an absolutely amazing library when doing all things text with skia: https://github.com/toptensoftware/RichTextKit
