### ISSUE TITLE
I can not compile--> (WindowsSample) VS2013

### ISSUE THREAD

**Issue by EAxp3** [mono/SkiaSharp#180]
I can not compile sample--> (WindowsSample)
[WindowsSample](https://github.com/mono/SkiaSharp/tree/master/samples/WindowsSample)

when open the code mark many mistakes.

I'm using:
Visual Studio Ultimate 2013 Update 4
Windows 10 Anniversary Update x64

It is necessary visual studio 2015?

please someone help me.
I want to learn how to use this library in WindowsForms and WPF.
I want to create a photo viewer using this library in forms or WPF.

**Comment by mattleibow** [comment]
Hi @EAxp3, thanks for giving SkiaSharp a go.

You might be having a problem because you are using the not-yet-complete on the master branch. As we add more features, we do it on the master branch - sometimes things are broken or rely on code that is not yet finalized. I would suggest downloading the samples from a "release". The latest is the v1.54.1 release: https://github.com/mono/SkiaSharp/releases/tag/v1.54.1

You can download the repo there using the "Source code (zip)" link. this will also give you a much smaller download as it doesn't include the very large external dependencies.

Once downloaded, the samples will download all the correct NuGet packages and you problems should go away.
