### ISSUE TITLE
Add pixel modification support for index8 bitmaps

### ISSUE THREAD

**Issue by Tylerflick** [mono/SkiaSharp#186]
This should be as simple as exposing `void SkBitmap::setPixels(void* p, SkColorTable* ctable)` for setting the pixel values, and adding index8 support to `sk_bitmap_get_pixel_colors `.

I don't believe that the SkBitmap class supports modification to a single pixel when the backing color type is index8.

PR adding support #196

**Comment by Tylerflick** [comment]
Opened a [PR](https://github.com/mono/skia/pull/36) on mono/Skia to add support for the fix.

**Comment by mattleibow** [comment]
@Tylerflick I just was thinking, since we don't support setting a specific pixel color for Index8, maybe we should throw (in managed code) an exception if someone calls set pixel with an Index8 color type.

If support is added, we just need to remember to remove that check. What do you think?

**Comment by Tylerflick** [comment]
I like that idea.

We should also probably add a guard to `SetColorTable(SKColorTable ct)` & `SetPixels(IntPtr pixels, SKColorTable ct = null)` if the ColorType isn't Index8.

I also need to add some documentation to these new methods.

**Comment by mattleibow** [comment]
to update the docs - it will fail because you need to be running on CI (both mac and Windows bits), but you can still generate the things for SkiaSharp.dll (where we are working). Basically, run this target:

    .\bootstrapper.ps1 -Target update-docs

This will mostly work, but you can just use the bits that you added inside the xml docs. This is a bit complicate to explain, but if you aren't running this for all the platforms, then it removes those types. So for you, run the command and then just add the `/docs/en/SkiaSharp/*.xml`. The other files will all be messed up because some types aren't there - so just revert them.

The final result will be a fairly small diff with new sections like this:

```xml
    <Member MemberName="ColorTable">
      <MemberSignature Language="C#" Value="public SkiaSharp.SKColorTable ColorTable { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class SkiaSharp.SKColorTable ColorTable" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>1.53.0.0</AssemblyVersion>
        <AssemblyVersion>1.54.0.0</AssemblyVersion>
        <AssemblyVersion>1.54.0.0</AssemblyVersion>
        <AssemblyVersion>1.55.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>SkiaSharp.SKColorTable</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Gets the color table of the bitmap.</summary>
        <value>
          <para></para>
        </value>
        <remarks>
          <para></para>
        </remarks>
      </Docs>
    </Member>
```

That is what the docs really are. In you case, with the PR, there should be about 3 members. 

Good Luck 😸

**Comment by Tylerflick** [comment]
Docs and guard clauses added to the new methods 👍.

**Comment by mattleibow** [comment]
I just caused a conflict, sorry :)

**Comment by mattleibow** [comment]
I merged the native mono/skia bits. Just a small thing for the managed bits: https://github.com/mono/SkiaSharp/pull/196#pullrequestreview-9104423
