### ISSUE TITLE
SKData.AsStream sometimes returns corrupted image

### ISSUE THREAD

**Issue by daniel-luberda** [mono/SkiaSharp#194]
`SKData.AsStream` returns corrupted images, not all the time, but once in a few tries. Tested on iOS (emulator). 

```C#
using (var image = SKImage.FromBitmap(bitmap))
using (var data = image.Encode(SKImageEncodeFormat.Png, 80))
{
	var stream = data?.AsStream();
	// then process encoded PNG - sometimes is corrupted
}
```

However, this is working just fine (without any issues):

```C#
using (var image = SKImage.FromBitmap(bitmap))
using (var data = image.Encode(SKImageEncodeFormat.Png, 80))
{
	var stream = new MemoryStream();
	data.SaveTo(stream);
	stream.Position = 0;
	// then process encoded PNG - without any issues
}
```

Full code here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs#L80-L98

**Comment by mattleibow** [comment]
I had a look and the reason for that is quite simple actually. The `SKData.AsStream()` just wraps the data as a stream. Because you are disposing the data object, the stream is actually now rapping a chunk of memory that could be anything.

There are two ways to solve this, one of which you do already. Either **copy** the data to a stream, using `SKData.SaveTo(Stream)` or you make sure the data object lives for as long as the data object. As you can't really do the latter when you are exposing the `Stream` and not the `SKData`, copying is the only way to go about this.

In the next version I have added an overload that will allow you to get the stream, and when the stream is disposed, the underlying data will be too: https://github.com/mono/SkiaSharp/commit/f2875d86f92c39e8cf1e4a4bb7ac2c5bb000d4b7?w=1

In your case, you could write this:

```csharp
using (var bitmap = new SKBitmap((int)sizeX, (int)sizeY)) {
    using (var canvas = new SKCanvas(bitmap))
    using (var paint = new SKPaint()) {
        // draw on canvas
    }
    using (var image = SKImage.FromBitmap(bitmap)) {
        var data = image.Encode(SKImageEncodeFormat.Png, 80)); // don't dispose
        var stream = data?.AsStream(true);
        return stream; // this will dispose 'data' in Stream.Dispose()
    }
    // 'bitmap' can be disposed as the data is a copy of the encoded bitmap
}
```
