### ISSUE TITLE
[BUG] Wiki dotnet cake

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#2019]
`> dotnet cake` is now `> dotnet-cake`

```
PS C:\Users\small\source\repos\AndroidUI-SkiaSharp> dotnet cake --target=everything --skipExternals=all
Run "dotnet tool restore" to make the "dotnet-cake" command available.

PS C:\Users\small\source\repos\AndroidUI-SkiaSharp> dotnet-cake --target=everything --skipExternals=all
The assembly 'Cake.Xamarin, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by mattleibow** [comment]
Using `dotnet-cake` uses the global install of the tool which may be an incorrect version. `dotnet cake` using the tool that is decided by the SkiaSharp repo.

If you run `dotnet tool restore` before executing the `dotnet cake` command, it will install all the required tools. You can also use the `.\bootstrapper.ps1 --target=everything --skipExternals=all` to automatically do everything for you.

If this is related to #2020 then I think it is because you did not run the exact command described in the error message,
