### ISSUE TITLE
SKCanvasViewRenderer is internal

### ISSUE THREAD

**Issue by SteaI** [mono/SkiaSharp#218]
i want add 'OnGlobalLayoutListener' on SKCanvasView in Xamarin Forms Android.
But SkiaSharp.Forms SKCanvasViewRenderer is defined internal.

**Comment by mattleibow** [comment]
I am looking at this, there are a few things to do before making the type public. However, are you able to see if you can attach the handler using effects: https://developer.xamarin.com/guides/xamarin-forms/effects/introduction/

You can do that and just add the effect for Android - no need to create a custom renderer. You can access the native control and even cast it to `SKCanvasView`

**Comment by SteaI** [comment]
I already solved it by edited the SkiaSharp open source, but thanks for the good way.

**Comment by mattleibow** [comment]
In a recent commit (https://github.com/mono/SkiaSharp/commit/af51bb49d32e4e5dcf7048c00db18a94872438b0), I changed the visibility to public so that custom renderers can be created.

This is just the basic access to the types, so you can't control some things (intercepting existing events, controlling the render loop on GL views, change the actual underlying native view). I was going to do a bit more, but there are a few things that need thought. So, I decided to just allow for customizations on to of what's there for the first release.

I am closing this issue as my commit actually adresses the feature, and other changes should be on a new issue

**Comment by mattleibow** [comment]
I created a simple sample app that uses custom renderers: https://github.com/mattleibow/SkiaSharpFormsRendererDemo

**Comment by SteaI** [comment]
WOWWWW!! Thanks for response. This is what I was going to do.
