### ISSUE TITLE
Expose SKMask Class

### ISSUE THREAD

**Issue by Tylerflick** [mono/SkiaSharp#220]
I'm requesting API support for SKMask struct and SKBitmap::InstallMaskPixels.

The SKMask struct allows for a lightweight method for handling alpha masks.

**Comment by Tylerflick** [comment]
PR's submitted for support (https://github.com/mono/SkiaSharp/pull/221, https://github.com/mono/skia/pull/46)

**Comment by mattleibow** [comment]
@Tylerflick I made a small change to the `SKMask`. Because a struct is not so great with native objects (the GC will not dispose the struct, as it doesn't have a finalizer), I updated the type to not automatically create/dispose the image. The type now just holds a plain `IntPtr`. I added a `Create` method that will copy the bytes into an unmanaged memory location. The user will also have to manually destroy the memory.

Basically, instead of `new SKMask(bytes)`, which called `AllocImage()`, you need to use `SKMask.Create(bytes)`. Then, you need to call `mask.FreeImage()` to release the memory.

This is also good for managed interop which has no need to free the memory:

```
fixed (void* ptr = bytes) {
    mask = new SKMask(ptr, ...);
}
```

If you want the nice dispose pattern with `using` blocks, you can make use of `SKAutoMaskFreeImage` (I copied the logic from the C++ code):

```
var mask = new SKMask(ptr, ...);
using (new SKAutoMaskFreeImage(mask.Image)) {
    // do stuff
}
```

Again, you won't use the `using` statement if you are using interop with the `fixed` block as you don't need to free memory - the GC will get to it.

**Comment by Tylerflick** [comment]
Thanks for doing this. I was having a bit of trouble figuring out how to handle that native buffer.
