### ISSUE TITLE
[BUG] Build issues concerning libSkiaSharp

### ISSUE THREAD

**Issue by file-acomplaint** [mono/SkiaSharp#2200]
**Description**
Hello folks, thank you for the cool open source software! I am using SkiaSharp inside the game engine Godot for [this](https://github.com/file-acomplaint/GodoTeX). On Windows, it works just wonderful. Now, building the same code on Linux, this exception is raised, sadly without further information:

`
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
`

**Version Information**
The `.csproj` is

```xml
<Project Sdk="Godot.NET.Sdk/3.3.0">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>GodoTeX</RootNamespace>
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.1-preview.91" />
    <PackageReference Include="CSharpMath" Version="0.5.1" />
    <PackageReference Include="CSharpMath.SkiaSharp" Version="0.5.1" />
  </ItemGroup>
</Project>
```

I have also tried using version 2.80.4 of SkiaSharp, using SkiaSharp.NativeAssets.Linux, and specifying `<PreferredNativeSkiaSharp>`.

The output of  `ldd` on `bin/Debug/x64/libSkiaSharp.so` is

```
        linux-vdso.so.1 (0x00007ffd4ced6000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb717155000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb717150000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fb716519000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fb716200000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb71717c000)

```

This is running on Arch Linux 5.18.14. I have also tried it on a clean install of Ubuntu, with precisely the same result.

I would be very grateful for any and all feedback.

**Comment by mattleibow** [comment]
I am not able to repro this: https://github.com/mattleibow/SkiaSharpArchLinux

> NAME="Arch Linux"
> PRETTY_NAME="Arch Linux"
> ID=arch
> BUILD_ID=rolling
> VERSION_ID=TEMPLATE_VERSION_ID
> ANSI_COLOR="38;2;23;147;209"
> HOME_URL="https://archlinux.org/"
> DOCUMENTATION_URL="https://wiki.archlinux.org/"
> SUPPORT_URL="https://bbs.archlinux.org/"
> BUG_REPORT_URL="https://bugs.archlinux.org/"
> LOGO=archlinux-logo
> 
> 5.10.102.1-microsoft-standard-WSL2
> Hello, Bgra8888 World!
>

**Comment by mattleibow** [comment]
Oooh, sorry. I was sure I checked public.

Yeah, the build engine may be excluding the required files?

Can you maybe link to a repro repo :) so that I can check it out. And the fact that it does not work on Ubuntu which is what my CI uses for linux testing is really showing that the Gadot is doing something fishy... A repro will help.

**Comment by file-acomplaint** [comment]
Great, now I can see it! Hm, the only difference that I could see is the different target framework and that I didn't include SkiaSharp explicitly. I've tried changing both, without effect. 

If it's minimal enough, I have prepared [this](https://github.com/file-acomplaint/GodoTeX) for reproducing it now. If opened in Godot Mono, it will show a warning like 'couldn't load add on', which is OK. Simply clicking on build in Godot should then reproduce the error. (Perhaps reloading the add-on in Project Settings>Plugins is needed) 

I sadly don't know anything about devops, so I can't provide something that runs on docker or the like. I also wouldn't know how to reproduce outside of Godot.

But f I should come up with a simpler repo, I can do that!

**Comment by mattleibow** [comment]
OK, so I found the issue. For some reason, Godot does something and the `c` (libc) library no longer is the thing I expect. Not sure why, but it is fixable. I fix this in #2213 and I will get this out ASAP.

There is a workaround that you can use to override this detection.

Add this to a new file:

```cs
static class InitSkia
{
	static InitSkia()
	{
		Console.WriteLine("Fixing SkiaSharp...");
		var assembly = typeof(SkiaSharp.SkiaSharpVersion).Assembly;
		var config = assembly.DefinedTypes.FirstOrDefault(t => t.Name == "PlatformConfiguration");
		var overrideProp = config.GetProperty("LinuxFlavor");
		overrideProp.SetValue(null, "linux");
		Console.WriteLine("Fixing SkiaSharp complete.");
	}
	
	public static void Init() {}
}
```

Add this to the code somewhere before the render happens. I added to the beginning of the `Render()` method, but you can add it anywhere:

```cs
InitSkia.Init();
```

This workaround overrides the detection with the explicit "linux" value. Unfortunately, I have to use reflection because I did not yet merge #1856 yet. I forgot about that one :( and will try get it in ASAP as well. Once this is merged you have a much simpler (albeit no longer necessary) way to set the value:

```cs
SkiaSharp.Internals.PlatformConfiguration.LinuxFlavor = "linux";
```

But, as I said, #2213 will fix the bug and all this is not necessary.

**Comment by file-acomplaint** [comment]
Oh wonderful, thank you so so much! It works like a charm. I feel indebted to you!

**Comment by mattleibow** [comment]
I pushed out an update to nuget.org and preview 108 works out hte box and even in the editor :)

Have fun!
