### ISSUE TITLE
External Build skipped due to a criteria

### ISSUE THREAD

**Issue by JimSEOW** [mono/SkiaSharp#226]
![powershell_2017-01-29_15-56-56](https://cloud.githubusercontent.com/assets/8244633/22404988/bafc3b44-e63b-11e6-8343-ff75f67b6f87.png)

- externals-angle-uwp; uwp; windows were skipped due to a criteria
![powershell_2017-01-29_15-59-39](https://cloud.githubusercontent.com/assets/8244633/22405005/0184c4c8-e63c-11e6-8e93-dbb76ec1f19f.png)

I checked the directories, it seems that all libraries were built.

=> What could be the criteria that make the script skip these external libraries?

**Comment by mattleibow** [comment]
It may be because the libraries were built on a previous run? The native bits take a long time to build, so I skip them on consecutive runs. To force a rebuild of them, there are a few things you can do:

1. clean: `./bootstrapper.ps1 -Target clean`
2. just delete the final libs: `native-builds\lib\<platform>\<arch>`

If you are working on the native bits, I find it quicker to just temporarily comment out the check (the same for any platform):
https://github.com/mono/SkiaSharp/blob/6c235df4c8b92078a4cac8b1397e51a6002ab79c/cake/BuildExternals.cake#L152-L154

And, you can also just do all your testing on a single arch by commenting out a few lines:

https://github.com/mono/SkiaSharp/blob/6c235df4c8b92078a4cac8b1397e51a6002ab79c/cake/BuildExternals.cake#L179 or for UWP https://github.com/mono/SkiaSharp/blob/6c235df4c8b92078a4cac8b1397e51a6002ab79c/cake/BuildExternals.cake#L216-L217

This way you only build one arch and the project files aren't rebuilt each time. This allows the project to be built with just the code changes, and not a full rebuild. (If you are making changes to the gyp, gypi or gn files, then you need to rebuild the projects.)
