### ISSUE TITLE
Too many external frameworks leaking into codebase, reducing maintainability

### ISSUE THREAD

**Issue by danwalmsley** [mono/SkiaSharp#2288]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/4672627/196970510-6b3d956c-b589-4ce8-b3a2-c29df0890690.png">

This main repo should not have a single mention of other frameworks. The project doesnt have the maintainers or resources to keep up.

Its a real shame because its a promising project, but its now so unmaintainable it cannot be updated.

Proposal: Remove all of those extra views and keep to just the bindings...

Blazor, uno etc can maintain their own views out the main repo, and we can get Skiasharp back updated again.

**Comment by mattleibow** [comment]
Maybe we can move the view _code_ into the github.com//mono/SkiaSharp.Exteneded repo. This way SkiaSharp is just a binding and then the other repo consumes things via a nuget.

**Comment by mattleibow** [comment]
This will also help with maui as maui.graphics.skia depends on this repo, but this repo depends on maui for samples...

**Comment by mattleibow** [comment]
Just thinking about this over the last few days and moving all views out makes it hard to test as there is no UI part.

We might be better off removing the non-core features - like Maui, Uno, X.F and the rest. But, we would keep the iOS, Android and maybe even GTK.

Since those platform views are pretty simple and don't really have features, we can have a much easier time adding/fixing things in the Uno/Maui worlds without having to build the ENTIRE dev machine and set of requirements.

Maybe we could move the views out and have the samples/testing in the core SDKs just be offscreen things... We can draw a line anywhere - but maybe we just need to see the minimum needed for testing skia on devices...
