### ISSUE TITLE
XF controls using SKIA do not render using the Visual Studio 2015 or 2017 Xamarin Forms Previewer

### ISSUE THREAD

**Issue by kdawg1406** [mono/SkiaSharp#234]
We are unable to get any control that uses SKIA to render in the Visual Studio 2015 or 2017 Xamarin Forms Previewer.

Any suggestions for getting our controls to render in the preview?

Best,

Karl

**Comment by mattleibow** [comment]
Right now there are a few issues when the previewer tries to load a view that uses an underlying native (.so/.jar/.a) library: https://bugzilla.xamarin.com/show_bug.cgi?id=47865

**Comment by renzska** [comment]
Any update on this? I'm running into the same issue.

Thanks!

**Comment by mattleibow** [comment]
Just tested in Xamarin Studio and Visual Studio 2017. The previewer no longer crashes. Due to limitations in the previewers with native assets, the paint events are not invoked (the views will be blank).

**Comment by renzska** [comment]
Can you describe what the limitations are? Is there a possibility of overcoming these limitations in the future? It would be a tremendous help when developing apps to be able to see what's going on using the Xamarin Forms Previewer. As of right now, it makes it quite difficult.

**Comment by mattleibow** [comment]
Great to hear that the fixes are working for you.

The current limitation is that at this time, the designers and previewer is unable to load native C/C++ libraries. As SkiaSharp is basically a thin wrapper for a native library, SkiaSharp cannot really be used to view drawings inside a designer. The view itself can still be seen and manipulated, but the painting is not available.

This is purely a designer/previewer issue, and we are working with the respective teams to resolve this - not only for SkiaSharp, but for other native libraries as well.

Are you having specific issues? If you need to preview drawings I sometimes use the Xamarin Workbooks to help out: 

 - Workbooks: https://developer.xamarin.com/guides/cross-platform/workbooks/
 - SkiaSharp Workbook: https://developer.xamarin.com/workbooks/graphics/skiasharp/introduction/introduction.workbook

We have also been working on a drawing designer that allows you to manipulate shapes as you would with a graphics program, but then export as SkiaSharp code:

 - Kimono Designer: https://github.com/xamarin/KimonoDesigner

I hope these will help make things easier, but please let me know if you are having specific issues.

**Comment by renzska** [comment]
So my desire for SkiaSharp to be able to render in the designer/previewer has to do with controls that have been built using SkiaSharp. My quick example is a passcode screen where I have multiple CircleView objects built using SkiaSharp and I need to see how all the controls look together when applying my grid layout and sizing, etc. I currently have to run the app in the simulator to see how they look after each XAML change.

I actually found the Kimono Designer earlier this week and that looks to be a great tool to build out the graphics pieces, but again, my desire is to see how they look when Xamarin.Forms lays out my pages.

Thanks for the detailed response and the hope that this functionality may come in the future. 

As a side, NControls (https://github.com/chrfalch/NControl) is trying to gauge the desire for using SkiaSharp instead of NGraphics: https://github.com/chrfalch/NControl/issues/75

**Comment by eltiare** [comment]
I'm getting this error on MacOS: 
![image](https://user-images.githubusercontent.com/3036/42103023-0bf4bb90-7b85-11e8-81f9-be8ea98555a3.png)
