### ISSUE TITLE
[QUESTION] SKTypeface.FromStream in MAUI

### ISSUE THREAD

**Issue by JoacimWall** [mono/SkiaSharp#2426]
Hi 
I am porting a Xamarin app to Maui.
Today we do it like this in Xamarin. 
```
var assembly = IntrospectionExtensions.GetTypeInfo(typeof(SkiaSharpHelper)).Assembly;
Stream stream =assembly.GetManifestResourceStream("LiberoClub.Resources.Fonts.babyplanetregular.otf");
_babyPlanetRegular = SKTypeface.FromStream(stream);
```

but this is not working when the font files are of type MauiFont in the projectfile.
```
<!-- Fonts -->
<MauiFont Include="Resources\Fonts\*" /> 
```

So to get this to work I need to add this line for every font in the project. 
```
<ItemGroup>
	  <EmbeddedResource Include="Resources\Fonts\babyplanetregular.otf" />   
</ItemGroup>
```

Is there some way to do this where I don't need to manual add the font twice.

//Thanks Joacim

**Comment by mattleibow** [comment]
Maybe MAUI should get an API to get a stream for a font and/or image...

**Comment by DennisWelu** [comment]
It would be really cool if you could use SKTypeFace.FromFamilyName(fontFamilyName) where fontFamilyName will reference names as registered custom fonts in MAUI. Then you could skip the stream loading etc. But I'm thinking that would be difficult because the SKTypeFace implementation is "probably" just looking at registered system fonts.

**Comment by activa** [comment]
> It would be really cool if you could use SKTypeFace.FromFamilyName(fontFamilyName) where fontFamilyName will reference names as registered custom fonts in MAUI. Then you could skip the stream loading etc. But I'm thinking that would be difficult because the SKTypeFace implementation is "probably" just looking at registered system fonts.

SKTypeFace.FromFamilyName() works perfectly in Xamarin Forms apps that have embedded fonts. Unfortunately, it doesn't work in MAUI

**Comment by LuStefanoX** [comment]
It's been a while since the last post, but if anyone still needs it, this is how I solved it in MAUI
I have packed the ttf file in the "Fonts" folder

var textPaint = new SKPaint();
using var data = await FileSystem.OpenAppPackageFileAsync("YourTTFFile.ttf");
textPaint.Typeface = SKTypeface.FromStream(data);

canvas.DrawIconifiedText(IconFonts.PowerStandby, x, x, textPaint);

**Comment by mattleibow** [comment]
Thanks for that update @LuStefanoX 

I believe this is the correct way to get fonts. For raw assets, this will also work. For image, this is a bit harder since they are packaged in a special way on Android but also have scaling suffixes. However, this issue is for fonts and I think your code is the correct and best way.

**Comment by albilaga** [comment]
> It's been a while since the last post, but if anyone still needs it, this is how I made a workaround for MAUI I have packed the ttf file in the "Fonts" folder
> 
> var textPaint = new SKPaint(); using var data = await FileSystem.OpenAppPackageFileAsync("YourTTFFile.ttf"); textPaint.Typeface = SKTypeface.FromStream(data);
> 
> canvas.DrawIconifiedText(text, x, x, textPaint);

@LuStefanoX do you successfully using this on android as well? Weird thing in my case sometime `FileSystem.OpenAppPackageFileAsync` throw File not found exception. Working well with `MauiAsset` but I don't want to duplicate the font if possiblle :(

**Comment by LuStefanoX** [comment]
@albilaga 
It works for me for Android and iOS.
- Did you add the font in the Font Folder and changed the property to "MAUIFont"?
- And did you add the fonts in the MAUIAppBuilder in MauiProgram.cs - class like this?
 `.ConfigureFonts(fonts =>{
    fonts.AddFont("nameOfYourFont.ttf", "nameOfYourFont"),
    fonts.AddFont("nameOfYourFont2.ttf", "nameOfYourFont2"),
   }`
