### ISSUE TITLE
Unable to do ExtractSubset

### ISSUE THREAD

**Issue by payoff** [mono/SkiaSharp#245]
I'm using a modified version id thumb generator that perform a crop to square using extract subst:
I've a Null Exception using the last version: 1.56.1.
The problem is when I use the **bitmap**, to do the resize.

       
```csharp
public static void SquareResize(Stream inputStream, int size, Stream outputStream)
{
    using (inputStream)
    {
        using (var managedStream = new SKManagedStream(inputStream))
        {
            using (var original = SKBitmap.Decode(managedStream))
            {
                int x = 0, y = 0, len = 0;

                if (original.Width > original.Height)
                {
                    x = (original.Width - original.Height) / 2;
                    len = original.Height;
                }
                else
                {
                    y = (original.Height - original.Width) / 2;
                    len = original.Width;
                }
                using (var bitmap = new SKBitmap(new SKImageInfo(len, len)))
                {
                    var ok = original.ExtractSubset(bitmap, SKRectI.Create(x, y, len, len));
                    try
                    {
                        using (var resized = bitmap.Resize(new SKImageInfo(size, size), SKBitmapResizeMethod.Lanczos3))
                        {
                            if (resized == null)
                                return;

                            using (var image = SKImage.FromBitmap(resized))
                            {
                                using (outputStream)
                                {
                                    image.Encode(SKImageEncodeFormat.Jpeg, Quality).SaveTo(outputStream);
                                }
                            }
                        }
                    }
                    catch(Exception e)
                    {
                        Console.WriteLine(e);
                        throw;
                    }
                }
            }
        }
    }
}
```

Any hint?
Thanks

**Comment by mattleibow** [comment]
I think I have found the problem and a solution (both temporary and permanent)

The problem is that the resize is trying to resize the bitmap's pixmap, and that is the null problem.

Before explaining the why, let me explain the parts. First, there is the `ExtractSubset`. This does not actually always make a copy of the pixels, but rather has a reference to the previous bitmap. This saves lots of space in memory.

Second, the resize actually happens with the bitmaps pixmap (the container for the pixels). Since the bitmap is now re-using the previous bitmap's pixels, it doesn't have its own pixmap yet.

You can force a bitmap to have it's own pixels by locking the pixels (this is the temporary solution):

```csharp
bitmap.LockPixels();
using (var resized = bitmap.Resize(...))
{
    // ...
}
bitmap.UnlockPixels();
```

It may even be better to use the auto locker in case of exceptions:

```csharp
using (new SKAutoLockPixels(bitmap))
using (var resized = bitmap.Resize(...))
{
    // ...
}
```

Now that we have the temporary solution, the real fix will be to first lock the bitmap in my resize method.

PS: I noticed another potential issue with the code:

```csharp
using (outputStream)
{
    // ...
}
```

That will dispose the output stream. This may be desired, but if not, you can rather just flush it:

```csharp
outputStream.Flush();
```
