### ISSUE TITLE
[FEATURE] DrawText with Span<> so we don't need to GC.

### ISSUE THREAD

**Issue by cyraid** [mono/SkiaSharp#2460]
Be able to draw from the stack via Span. This would result in no extra string allocates on my end, just an internal copy for that string in the stack. I did a heap trace and found I was creating so many new strings per second, and I realized oh yeah, I'm creating a new string each time.

**Describe the solution you'd like**

```csharp
ReadOnlySpan<char> fpsText = $"{fps}fps";
DrawText(fpsText, 0, 0, font, paint);
```

Being able to `DrawText` like that would be nice.

**Describe alternatives you've considered**

I could cache the fpsText, but it may wildly change on some other systems and need up to MAXFPS strings.

**Additional context**

Too much GC's result in large hiccups, it'd be nice to focus on reducing some of these bottlenecks to result in a smooth experience.

**Comment by mattleibow** [comment]
`DrawText` appears to have a string overload because that was the old API and it is convenient, however, no matter what API you use on the `SKCanvas` API, it creates a `SKTextBlob` object under the hood and draws using that.

The `SKTextBlob` supports spans, so maybe that is how you can avoid hidden allocations?

This is sort of what the implementation in `SKCanvas` looks like:

```cs

public void DrawText (string text, float x, float y, SKFont font, SKPaint paint)
{
	using var blob = SKTextBlob.Create (text, font);
	if (blob == null)
		return;
	DrawText (blob, x, y, paint);
}
```

**Comment by cyraid** [comment]
It was more so that the garbage collector wouldn't need to much to do. I'm not sure if SkiaSharp was designed with realtime rendering of every frame in mind, but those GC cleanup hiccups are very noticeable (as just drawing text is creating new objects every time). Having an allocation free setup would help with this. :) (That's why using span instead of creating an object, would use local stack space)

**Comment by Gillibald** [comment]
If you mutate your text buffer you always need to allocate a new SKTextBlob. This is how it works. If you don't mutate reuse the text blob.

**Comment by mattleibow** [comment]
The issue is that string are not super draw friendly. Fonts and things require some shaping and glyphs. Technically, skia only really supports glyphs, so string - especially unicode - gets converted into a series of positions glyphs. So changing the text will trigger a change of the underlying glyphs.

And, there are more lies. text blobs are created using a `SKTextBlobBuilder`.

The builder allows for allocations of "runs" and then it is snapped off into text blobs, which are then drawn. Text blobs are read only as well, so updating is not possible -and it would not be simple to do as the text blob is a collection of runs which are collections of glyphs and positions.

However, you can make a text blob builder and keep that one alive, then generate blobs off that using spans. However there are also the `SKRunBuffer` objects that maybe are getting in the way of the GC as that does not do anything special. It just wraps a native struct and provides a way to add the contents of a run. It does not have any handles, so it was just a plain C# object.

Are you able to verify that the hiccups are from the text drawing? Can you get some stats on what objects are actually being cleaned up as there are a few layers to this ...

**Comment by cyraid** [comment]
Sorry @mattleibow , I'd really like to follow up with this as I might be using more of it in the future, but I'm working on a different project for a client at the moment. I will provide some insight though: It's probably not just the Text Drawing that is allocating objects, I'd have to look more into your library. But it would be smooth for a few seconds, huge stutter, continue for a bit, again huge stutter. C# is at least providing spans and such for allocation-less code, and I think that's pretty important in any realtime graphics library.

**Comment by ScrubN** [comment]
If it's alright, I would like to also advocate for a DrawText overload with the signature:
```cs
public void DrawText(ReadOnlySpan<char> text, float x, float y, SKPaint paint)
```

I understand that an `SKTextBlob` will always be allocated, however I find it can be nicer to do text creation/manipulation via spans instead of strings and would prefer to directly pass my spans without allocating them as strings, just for them to be referenced as spans again by `SKTextBlob.Create()`:

https://github.com/mono/SkiaSharp/blob/95c296bd9e8301205c7136de5670681fd1f24396/binding/Binding/SKCanvas.cs#L607-L611

https://github.com/mono/SkiaSharp/blob/7646bc1e68ec8711f1be9ff0547fa3d42f03a300/binding/Binding/SKTextBlob.cs#L32-L33

Part of my reasoning for requesting the overload instead of just writing an extension method is because of `SKPaint.GetFont()` being internal, which means either cloning the font on every call with `SKPaint.ToFont()`, unnecessarily holding on to a clone of the text paint's font for the duration of the renderer's lifetime, or accessing `GetFont()` via reflection, none of which are very desirable.
