### ISSUE TITLE
New stance on SVG support?

### ISSUE THREAD

**Issue by EnCey** [mono/SkiaSharp#258]
Do you plan to support SVG in SkiaSharp? If so, to what extent?

I already asked this question a little over a year ago here: #21 
Back then the answer was no, but now I noticed there is a SkiaSharp.Svg NuGet package. 

From looking at the source it appears to be rather basic support of SVG (?), are there plans to fully support the SVG spec?

**Comment by mattleibow** [comment]
We do want to support SVG, but this is no small task. SVG has a HUGE scope and detailed specification: http://www.w3.org/TR/SVG2/

At this point, SkiaSharp is more of wrapper for skia, with some added features. We will probably only support SVG in the same way skia does, when they do. This is not to say that someone (anyone really) can create a SVG engine that makes use of SkiaSharp as the rendering engine. Essentially, SkiaSharp is a 2D raster graphics engine, thus SVG and any vector system will have to be created from scratch.

I am looking at creating a SVG engine with inspiration for WebKit
https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/svg/

But... That is nowhere near a proof-of-concept even. I would not wait for this. There are a few SVG engines for .NET, but they aren't really cross-platform or mobile friendly.

**Comment by EnCey** [comment]
Alright, thank you for making that clear.

I believe I'm familiar with most/all the SVG engines available in .NET, but sadly none of them can "do it all", that's why I was curious what the SkiaSharp team's plans were in this regard.

I'll add your SVG engine to my watch list as well, even if it's still in early stages.

**Comment by YZahringer** [comment]
The support of these files would be great: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/

For example, dukechain.svg and image.svg are not rendered correctly.

**Comment by mattleibow** [comment]
Just for reference #120

**Comment by charlesroddie** [comment]
I don't understand this thread. There is SkiaSharp.SVG.
This went out of beta on 08 February 2017 according to https://www.nuget.org/packages/SkiaSharp.Svg/
Doesn't this simply mean that SkiaSharp supports SVG?

**Comment by EnCey** [comment]
@charlesroddie I doubt that SkiaSharp.SVG is anywhere close to supporting the full SVG 1 spec, purely from looking at the very compact source. 
It may be able to draw some basic shapes etc., but probably can't handle any of the advanced features of SVG like [clipping/masking](Clipping, Masking and Compositing) or [filters](https://www.w3.org/TR/SVG/filters.html).

**Comment by mattleibow** [comment]
I was asking on the skia forums, and it appears SVG work is underway, but not coming any time soon. This is because SVG support is really not a big requirement of either Chrome or Android.

They have right now a limited support:
https://github.com/google/skia/blob/2979b1a7eaffcdcf994e506caf743a9adf35b8ed/experimental/svg/model/SkSVGDOM.cpp#L279-L330

https://groups.google.com/forum/#!topic/skia-discuss/EuU-KljkQoE
> ... we are still working toward an SVG backend for Skia.  Practically speaking development is active, but we don't have exact time frame and the extent of support (have you seen the spec!?) is a bit unclear at this point.  As you mention, our biggest clients don't really need this support, but a handful of others have expressed interest, so it's something we're doing as possible to expand capability of the library.

I think it is safe to say that it is coming, eventually. I will endeavor to contribute to skia to get a fuller SVG support, but I can make no promises on this point. I think both skia and SkiaSharp have the same points in that SVG is large and not easy to implement. But, there are many low-hanging fruit that can be done to aid this process - for example, there is no radial gradient support yet, so that could be added, without too much work.

**Comment by mattleibow** [comment]
I just want to thank the community for there support and feature requests, and, to inform the world that SVG support has moved from this repository to one that is more appropriate: https://github.com/mono/SkiaSharp.Extended

This new repository will make it easier to develop libraries that use SkiaSharp, but don't really have to be built with the main library. In addition, there will be no need to first build all the native code, just to test a fix for some SVG case.

I opened a new issue there so that any updates can still be tracked. Please feel free to comment or open some PRs: https://github.com/mono/SkiaSharp.Extended/issues/2
