### ISSUE TITLE
[BUG] libjpeg-turbo => 3.0.1

### ISSUE THREAD

**Issue by satmandu** [mono/SkiaSharp#2667]
### Description

Libjpeg-turbo has been updated to 3.0.1: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.1

### Code

https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.1

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio Code (Linux)

### Platform / Operating System

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MFinkBK** [comment]
@mattleibow Maybe the bug fixes in libjpeg-turbo 3.0.1 fix the bugs in the issues #2650 #2666 #2643, too? The release notes talks about AArch64, which I think is used for 64-bit iOS builds?

**Comment by mlancione** [comment]
Any update on this? It is affecting all jpeg encoding on iOS devices with SkiaSharp 2.88.6.

**Comment by edobnet** [comment]
1

**Comment by mattleibow** [comment]
I tested 3.0.1 and the latest main and I think this is an issue in libjpeg-turbo. For now I am reverting to the latest 2.x series.

I had a look at the original security issue and it does not affect the 2.x series because 12-bit jpegs are not actually supported in our build. The 2.x series required the entire library to be either 8-bit or 12-bit, and we use 8-bit. The 3.x series allowed for both simultaneously.

The security issue was just reported for 2.1.90 (which seems like a 2.x series but is actually a 3.0 beta). The current stable version is 2.1.5.1 which is on a separate branch.
