### ISSUE TITLE
Forms SKCanvasView and Margins..

### ISSUE THREAD

**Issue by djcparker** [mono/SkiaSharp#267]
Not sure if it is me or the SK Views.
I set a Margin on the View to get some whitespace but it was completely ignored.

Next I wrapped it in a StackLayout (nasty I know) with a Margin on the StackLayout and the Canvas didn't render until I added VerticalOptions and Horizontal Options of "FillAndExpand".
Still it ignored the Margin.

Changed the Margin on the StackLayout to a Padding - BOOM - worked.

            
```
<StackLayout Padding="5" BackgroundColor="Orange">
       <skia:SKCanvasView  VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
             <skia:SKGLView.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding TappedCommand}"/>
            </skia:SKGLView.GestureRecognizers>
      </skia:SKCanvasView>
</StackLayout>

```

I'll try to find time to knock up a repo project.  In the meantime, any ideas?

**Comment by mattleibow** [comment]
If you can get a repo, then I can have a look. Also, what platform are you on?

I tested with the canvas as the root view, a child of a grid and stack layout. All adhere to the margin property.

For the case with no width/height or vertical/horizontal options, the canvas has no intrinsic size, since it is merely a drawing surface. In order to make sure it will be displayed, either a dimension must be specified, or a sizing option. For example, if you place it in a vertical stack layout, the width will stretch to the container width, and the height will fall back to 0. In this case, either use a grid to expand, or set an explicit height.

**Comment by djcparker** [comment]
Hi Matt, sorry, would help if I gave some more details 😊

This was on ios, iphone 5s. 
It was as the child of a grid, first row, single column.

Yeah, I looked at the code to see how it worked when I plugged it in.  It works awesome by the way!

I'll pull the code out and see if I can make it repo what I saw.

Thanks.

**Comment by mattleibow** [comment]
Did you managed to get a test case, I wasn't able to repo with a grid either.

**Comment by djcparker** [comment]
Working on it...  I can repo it in the app every time... Have a half finished stripped down copy of the main view.  Been caught in meetings and release planning the last couple of days, will get to it this week for sure.

**Comment by djcparker** [comment]
@mattleibow there is something odd going on.  Something about padding and margin.  I'm not 100% convinced it is the SkiaView.  Totally get what you are saying about the canvas, makes perfect sense, it is definitely not that. 

I'm flat out with work so I'll close this for the moment while I spend some time convincing myself one way or the other :)

thanks for the help!

**Comment by mattleibow** [comment]
No prob.

I'll keep an eye out for any issues similar to this, just in case. But, as soon as you have a repro let me know.
