### ISSUE TITLE
Wrap SkBitmap::setAlphaType

### ISSUE THREAD

**Issue by ikolev21** [mono/SkiaSharp#277]
Please wrap the native method SkBitmap::setAlphaType()
There's currently no simple and fast way to add an alpha channel to a bitmap (e.g. after loading it from a file). Only solution I could think of was to copy the bitmap pixel by pixel, which takes about a second for larger ones.

Thanks.

**Comment by mattleibow** [comment]
Before I add this, I wanted to check that you are aware of the fact that you can tell the decoder what image configuration that you want.

Instead of `SKBitmap.Decode(string path)`, you can use the overload: `SKBitmap.Decode(string path, SKImageInfo info)`

https://developer.xamarin.com/api/member/SkiaSharp.SKBitmap.Decode/p/System.String/SkiaSharp.SKImageInfo/

This will result in the image being loaded and converted into the desired color type and alpha type in a single decode operation.

The `SkBitmap::setAlphaType(...)` function does not actually do anything except switch the alpha type field, leaving the pixel data the same. This means that by changing the alpha type, the pixel data may be "different". For example, if you switch the alpha type from premultiplied to unpremultiplied, the color has effectively changed, since the color is related to the alpha value.

**Comment by ikolev21** [comment]
Ah, thanks for the info, I should have looked at the implementation of setAlphaType, in that case it won't do the job.
OK, I'll try Decode with ImageInfo.

**Comment by ikolev21** [comment]
I had missed your comment about changing the alpha type by using CopyTo. I had already tried that, it changes the alpha type of the target bitmap to match the type of the source, so it doesn't work.

Decode with a specified SKImageInfo does work. The only small inconvenience is that I need to open the stream twice, once to read the bounds and another time to read the image (since SKImageInfo wants to be given the image bounds).

**Comment by mattleibow** [comment]
Ah, in that case, you can use the `SKCodec` directly with an extra step:

```
// open the codec
var codec = SKCodec.Create(stream);

// get the dimensions from the codec
var info = codec.Info;

// create the bitmap (use the dimensions and optionally any desired color/alpha type)
var bitmap = new SKBitmap(info.Width, info.Height);

// decode the bitmap
codec.GetPixels(bitmap.Info, bitmap.GetPixels());
```

**Comment by ikolev21** [comment]
Thanks, this works and is indeed better.

**Comment by mattleibow** [comment]
I'll close this as this solves your problem, and I am not really wanting to wrap `SkBitmap::setAlphaType`. 

Feel free to reopen if this is needed.
