### ISSUE TITLE
[BUG] iOS 18 Chinese rendering bug

### ISSUE THREAD

**Issue by cho-trackman** [mono/SkiaSharp#3029]
### Description

I've experiencing this regression on iOS 18 when drawing the degree symbol °.

## iOS 17.5
![iOS 17](https://github.com/user-attachments/assets/975ca078-d846-4129-b072-103b6af4d8e7)

## iOS 18.0
![iOS 18](https://github.com/user-attachments/assets/dfe40b19-cc34-41c8-93c4-c6475f801f38)

### Code

Simple project to reproduce: https://github.com/cho-trackman/SkiaIos18Bug

### Expected Behavior

A normal looking degree symbol (°). It works on all iOS versions prior to 18. It also works in Japanese and Korean on iOS 18.

### Actual Behavior

You'll see different character than a degree symbol.

### Version of SkiaSharp

2.88.8 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Other (Please indicate in the description)

### Platform / Operating System

iOS

### Platform / Operating System Version

iOS/iPadOS 18.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cho-trackman** [comment]
I've just added a CoreGraphics part to test repo (https://github.com/cho-trackman/SkiaIos18Bug), but also realized that maybe it should have been done in CoreText to reflect how Skia is drawing (I don't know).

**Comment by cho-trackman** [comment]
Sample project updated with CoreText as well.

## iOS 17.5
![Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-10-07 at 11 09 04](https://github.com/user-attachments/assets/2610085e-7a5e-44ff-9fd4-0d88e8f5d91a)


## iOS 18.0.1
![IMG_72A203CE458B-1](https://github.com/user-attachments/assets/2098ee41-13be-4c38-a371-737afc59f9f1)

**Comment by mattleibow** [comment]
Can you try the latest preview 3.118? I wonder if there has been an update in the engine.

**Comment by taublast** [comment]
If you ask me, what is to investigate here is how the PingFang SC font changed, the one shipped with iOS 18.
The fact that UILabel/Core-libs-whatever render that symbol means absolutely nothing in that regard, personally I would expect them to find the appropriate font for every glyph inside the text to render. While in the repro we look for appropriate font for the symbol `单` only.

An example of this is when you pass an emojy to a system label and specify a font where it doesn't exist. A normal behavior for such control would be to find an installed font where this glyph is present and render it. If you do same with skia low-level `DrawText` you won't get it rendered correctly if it's missing. It's by design, it's okay, low-level renderers dont have to provide hi-level logic for you.

So one probability is if that glyph is missing from PingFang SC shipped with iOS 18 this issue is to be closed.

To be able to render complex text with emojies and such glyphs without worrying about what font to use when glyph is missing some would use [RichTextKit](https://github.com/toptensoftware/RichTextKit), some would use DrawnUI `SkiaMarkdownLabel` [see example](https://github.com/taublast/DrawnUi.Maui.Demo/blob/cc06ec81b7a7fc374e90c401ccabb6c15ec2569d/src/Usual/MainPage.xaml#L166).

**Comment by cho-trackman** [comment]
Just tested on `3.118.0-preview.1.2` and the issue is still there. I will look into your other suggestions and come back with more info.

**Comment by cho-trackman** [comment]
> Also, what happens if you remove the Chinese character? The character might be causing an issue somehow.

The degree char gets drawn as below, removing it removes the rectangle with the circle inside.
![image](https://github.com/user-attachments/assets/f78dea2d-2e59-43f5-99f0-cf0e63c1921e)

**Comment by cho-trackman** [comment]
> So one probability is if that glyph is missing from PingFang SC shipped with iOS 18 this issue is to be closed.

Don't mix up Unicode and ASCII.

**Comment by cho-trackman** [comment]
I just stumbled upon this thread https://forums.developer.apple.com/forums/thread/758189.
An Apple dev claims:
> PingFang.ttc is no longer in /System/Library/Fonts/Core. iOS 18 has a new Chinese UI font.

That is crazy news to me :O

**Comment by cho-trackman** [comment]
This must be the issue:
![image](https://github.com/user-attachments/assets/8e58daef-3833-4e39-93cb-a97e6010fd99)
https://forums.developer.apple.com/forums/thread/758189?answerId=811700022#811700022
