### ISSUE TITLE
How would I scale image down to particular byte length?

### ISSUE THREAD

**Issue by bobekhj** [mono/SkiaSharp#398]
Hi, First of all, thank you so much for your hard work. The project is awesome. 

I was able to resize my image to a specific WidthXHeight, but I am wondering if there is a way to scale it down to specific MB size. For example, if an image is over 5MB scale it down to 5MB. What I've tried was to scale an image down by width %. So, I would take current MB size, see what percentage of it is 5MB, and then change the pixel width by that percentage. It works, but for example, for 25MB image it gives me an image of 3.5MB. What I am worried about, is an image that is 100MB, will not come down to under 4MB. 

I also **don't** want to resize it multiple times. For example, resize once, check if under 5MB, if not resize again. 

Do you have any ideas on how I could approach this problem?

Thank you,
Hubert

**Comment by entdark** [comment]
If you are talking about a raw image then its size in bytes is width*height*bits/8.
For example, if we have a 10x10 coloured image with 24 bits colour depth per pixel (or 8 bits per each of 3 RGB channel) then the image size is 10*10*24/8=300 bytes. (We devide by 8 to convert bits to bytes.)
If the given image is grayscale then it's most likely has 8 bits colour depth per pixel so its size is 10*10*8/8=100 bytes.
If you are working with `SKImageInfo` struct then just do something like that:
`SKImageInfo info = yourImage.Info;
int sizeInBytes = info.Width * info.Height * info.BytesPerPixel; //or info.BitsPerPixel / 8`

**Comment by mattleibow** [comment]
It gets a bit more complex with encodings, such as bmp, jpg or png. Encoders apply compression, thus making the raw pixel size not very accurate. Also, the compression is very dependent on the actual pixel data rather than the amount of pixels - for example a solid white png 2K x 2K will save to about 9KB, but a 500x500 image with a few simple lines may exceed 100K

If CPU/time is not a limiting factor, then you can simply scale a bitmap and encode it. If it is too big, then you can just discard it and try again on the original. Rather than scaling the resulting image, just rescale the original - this should preserve quality.

**Comment by migueldeicaza** [comment]
This is best suited for discussion in the forums:

https://forums.xamarin.com/categories/skiasharp
