### ISSUE TITLE
SKTouchEventArgs.Handled not working?

### ISSUE THREAD

**Issue by mchiz** [mono/SkiaSharp#424]
Hi! My first time using github to report :)

I'm experimenting with the method "SKCanvasView.OnTouch" under UWP, and it seems like e.Handled is not working.

I have a SKCanvasView inside a ListView item, and I want it to capture the input events, but they are propagated to the ListView item (and it gets animated and selected if I click in my SKCanvasView).

As I see [in this file](https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs), it seems that the logic to stop the propagation is not implemented. The method "CommonHandler" returns the value correctly, but the UWP events ignore it.

As I see in the UWP documentation, it should be copied to "PointerRoutedEventArgs.Handled".

Am I right or am I missing something?

Thank you!

**Comment by mattleibow** [comment]
@mchiz Thanks for reporting this. It is also a good bug since you did some investigation yourself :)

I have a potential fix, see the attached NuGets. I now properly capture the pointer and all manipulation events when the mouse/finger is pressed. This will also prevent any other gestures from working if you have handled the pressed event until you release.

[SkiaSharp.1.59.4-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/297/Azure/processDownloadRequest/ArtifactsFor-297/a554f9bb294a3c4e23fa3bc2d31cd26e77bb3892/output/SkiaSharp.1.59.4-beta.nupkg)
[SkiaSharp.Views.1.59.4-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/297/Azure/processDownloadRequest/ArtifactsFor-297/a554f9bb294a3c4e23fa3bc2d31cd26e77bb3892/output/SkiaSharp.Views.1.59.4-beta.nupkg)
[SkiaSharp.Views.Forms.1.59.4-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/297/Azure/processDownloadRequest/ArtifactsFor-297/a554f9bb294a3c4e23fa3bc2d31cd26e77bb3892/output/SkiaSharp.Views.Forms.1.59.4-beta.nupkg)

**Comment by mchiz** [comment]
That's great! I tested it and it works great Thanks a lot!
