### ISSUE TITLE
The Platform needs to be either x64 or x86 to support Skia in Windows.			

### ISSUE THREAD

**Issue by pauldendulk** [mono/SkiaSharp#44]
When compiling Skia.WindowsDesktop.Demo with Visual Studio 2015 update 1 on Windows 8.1 I get the compile error 'The Platform needs to be either x64 or x86 to support Skia in Windows.'. What is going on?

**Comment by pauldendulk** [comment]
Simply select one of the alternative profiles from compile targets dropdown, like 'Debug|x86'. Perhaps the 'Release' and 'Debug' targets could be removed.

**Comment by KvanTTT** [comment]
Adding new Platform x64 in Configuration Manager solved my same issue.

**Comment by tdoneal** [comment]
I mean, why doesn't it just default to whatever the compiler is using if not specified?  Or at minimum, it should default to  x86...

**Comment by mattleibow** [comment]
This is related to #190 

The latest changes make a choice to use the native bits that the platform specifies (and just copies both for AnyCPU), but at an app level, the platform needs to be specified.

On your point of picking the default (aka, pick x86 or x64), we might be able to do something like that... I am just preparing to release the next version, but maybe I can fit this in:

How does adding a MSBuild property in the csproj sound? So, we can still target AnyCPU, but if there is something like this:

```xml
<OverrideSkiaSharpPlatform>x86</OverrideSkiaSharpPlatform>
```

then, instead of copying both platforms to the output location, it just pretends it is an x64 app?

**Comment by mattleibow** [comment]
The real question is what to do for Any CPU:

* Some people want both platforms
* Some people want the current platform

Also

**Comment by tdoneal** [comment]
I don't understand MSBuild at all, so I won't comment there.  I would just say it's worth it to not have to google an error message and waste time fixing configuration issues.  So whatever makes it "just work" is likely best (in my humble opinion).

**Comment by mattleibow** [comment]
Closing this as I have added logic to try and detect the correct libraries to copy with AnyCPU.
