### ISSUE TITLE
Linux x64 Native Library not in SkiaSharp 1.6.0 NuGet Package

### ISSUE THREAD

**Issue by jkoritzinsky** [mono/SkiaSharp#456]
I noticed that the Linux-x64 native binary didn't make it into the 1.6.0 SkiaSharp package. Was this intended? Any chance we can get a timetable for when it will be in-package or a patch release with it correctly added into the package?

**Comment by mattleibow** [comment]
Unfortunately, there are no plans to release the Linux library in the NuGet due to https://github.com/mono/SkiaSharp/issues/312.

However, there is a library that can be used on the release: https://github.com/mono/SkiaSharp/releases/tag/v1.60.0
Direct link: https://github.com/mono/SkiaSharp/releases/download/v1.60.0/libSkiaSharp.so
