### ISSUE TITLE
iOS: no touch.exit event fired

### ISSUE THREAD

**Issue by sonic1015** [mono/SkiaSharp#471]
When overriding the OnTouch function in iOS, and the touch moves outside the view, there is never any touch event fired. Thus, it's impossible to tell if the finger has been released or not.

This is a Xamarin.Forms project and I do not see this problem in Android or UWP.

My view is inside a Master-Detail page, so it's possible that the Master-Detail hijacked the touch event, but then we should get a touch-cancelled event. I'll see if I have time to create a reproduction later this week, but it's pretty simple to create.

**Comment by mattleibow** [comment]
I think this is because of the master-detail.

I just created a simple sample, and I can track the event even if it leaves the view. I then put it into a master-detail page, and then the events stopped as soon as I moved horizontally.

I am not sure if this is a bug with the Xamarin.Forms master-detail page hijacking events mid way, or if it is an issue with the SkiaSharp view. I will investigate further, but in the meantime, I managed to stop the gestures with `IsGestureEnabled = false`:

```csharp
void Handle_Touch(object sender, SKTouchEventArgs e)
{
	if (e.ActionType == SKTouchAction.Pressed)
	{
		// disable gestures when we start dragging
		var md = Application.Current.MainPage as MasterDetailPage;
		md.IsGestureEnabled = false;
	}

	// handle usual touch events

	if (e.ActionType == SKTouchAction.Released)
	{
		// re-enable gestures when we are finished
		var md = Application.Current.MainPage as MasterDetailPage;
		md.IsGestureEnabled = true;
	}
}
```

**Comment by mattleibow** [comment]
Based on the Xamarin.Forms team feedback, there is no way to intercept the Master/Detail gestures. The only way now is to either disable gestures globally, or to disable as soon as you start processing them somewhere else - such as when in a list view or other scrolling view.
