### ISSUE TITLE
App is not working properly due libSkiaSharp.so is not included in lib/armeabi folder of android apk

### ISSUE THREAD

**Issue by ysmoradi** [mono/SkiaSharp#554]
### Description

I've written an app using FFImageLoading's SVG & Xamarin forms. It uses SkiaSharp behind the sense.
In the result apk, libSkiaSharp.so is included in x86 but not included in armeabi! So app works properly on emulators, but not physical devices )-:

### Code

https://github.com/ysmoradi/XamarinFormsPrismSvgSample

### Expected Behavior

App should work fine on android devices as like as iOS devices/emulators & android emulators.

### Actual Behavior

App doesn't work on physical android devices only and you see no image.
To see the DllNotFoundException of libSkiaSharp.so, simply put a breakpoint at https://github.com/ysmoradi/XamarinFormsPrismSvgSample/blob/master/XamarinFormsPrismSvgSample/XamarinFormsPrismSvgSample/App.xaml.cs#L64

### Basic Information

- Version with issue:  1.60.0
- Last known good version:  )-:
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android: 8.1
- Target Devices:
  -   All physcial android devices above 4.4

**Comment by ysmoradi** [comment]
I was able to find a workaround for this issue by adding following to cs proj of android project.

```xml
<AndroidNativeLibrary Include="Lib\libSkiaSharp.so">
   <Abi>armeabi</Abi>
</AndroidNativeLibrary>
```

**Comment by mattleibow** [comment]
This is because `armabi` is very old (ARM6) and is not fully supported by SkiaSharp.
The current supported architectures are ARMv7A, ARM64, x86 and x64.

If possible, try selecting the `armeabi-v7a` option in the linker options and not using the old `armeabi` option.

Have a look here:
https://developer.android.com/ndk/guides/abis

As you can see, the old `armabi` is actually being removed entirely.

**Comment by ysmoradi** [comment]
Thanks so much :)
