### ISSUE TITLE
How to build Skia Sharp for only specific purposes? (e.g. for Font rendering only)

### ISSUE THREAD

**Issue by danReleases** [mono/SkiaSharp#583]
I'd like to build a skia sharp library file (dynamic/shared) that will only be used for Font rendering, thus reducing the size of my program's dependencies. However, I am unable to find a way to configure Skia Sharp to only include certain parts of it and would like to know if there is any guide I can follow for this.

**Comment by mattleibow** [comment]
SkiaSharp is already quite small, usually between 4-5 MB per platform architecture. The last few releases was actually a bug, see #573 and #584 

To further reduce the size, you could have a look at building your own. We typically include everything because we don't know what you are going to be using. You can remove quite a bit.

It is relatively simple to build your own: https://github.com/mono/SkiaSharp/blob/v1.60.2/cake/BuildExternals.cake#L532-L559

In most cases, it is just a case of running `gn` to generate the build files - here you pass along all the bits that you want. and then either run `ninja` or `ndk-build`. In fact, this is how most people build for Linux: https://github.com/mono/SkiaSharp/wiki/Building-on-Linux#building
