### ISSUE TITLE
Feature Request: Unscaled coordinates on touch

### ISSUE THREAD

**Issue by pfaucon** [mono/SkiaSharp#613]
### Description

In the file https://github.com/mono/SkiaSharp/blob/7576a8714ff0d29f2d89658a1ed47b8775be0593/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs

GetScaledCoord converts coordinates to a platform-specific scaled format.  While this is quite clever it is also remarkably difficult to use within the XF context.  I propose that on touch the touch location should be provided in both a scaled and unscaled format.  Failing that only unscaled values should be used.  This is related to feature-request/bug https://github.com/mono/SkiaSharp/issues/607

> VS bug [#736296](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736296)

**Comment by mattleibow** [comment]
Closing this because all the platforms actually use the opposite: raw pixel coordinates.

This is a bit different to the way Xamarin.Forms works with _view_ coordinates, however when drawing on a canvas, then pixels are more often used. Conversion is pretty simple if you are not doing any scaling - just use the display density. However, if there is scaling and panning, then you can preserve the current canvas matrix and work backwards to find the absolute coordinates.
