### ISSUE TITLE
Bitmap Negative Scale

### ISSUE THREAD

**Issue by davidmn** [mono/SkiaSharp#625]
### Description

Trying to apply a negative scale (to flip a bitmap) the bitmap disappears.

### Code

```
canvas.Translate( -imageWidth/ 2.0f, -imageHeight/ 2.0f );
canvas.Scale( -1, 1,0,0 );
canvas.DrawBitmap( bitmap, new SKPoint( 0.0f, 0.0f ) );
canvas.Scale( -1, 1, 0, 0 );
canvas.Translate( imageWidth/ 2.0f, imageHeight / 2.0f );
```

### Expected Behavior

The bitmap should mirrored around the y axis.

### Actual Behavior

The bitmap does not appear. I've done some translations to check and I don't think it's there.

### Basic Information

- Version with issue:  1.60.1
- Last known good version:  I don't think there is
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android: 8.1
- Target Devices:
  -   Pixel C

### Screenshots

A blank screen.

**Comment by mattleibow** [comment]
this is because you actually want to do the reverse. SkiaSharp drawing happens by transforming a matrix, and then drawing using that.

Your code actually asks for this:
 - move the origin off the screen (left and up) by half the bitmap width and height
 - flip the origin on the y-axis (this makes the right side of the image flip over to the far left)
 - draw the image with the top left at the origin (right now at the very far left of the screen)

What you want to do is the opposite, but there is also a shortcut way for flipping the matrix at the center:

```csharp
canvas.Scale(-1, 1, imageWidth / 2.0f, 0);
canvas.DrawBitmap(bitmap, 0, 0);
```

To do this in separate operations, you just need to translate the entire image to the right, and then flip:

```csharp
canvas.Translate(imageWidth , 0);
canvas.Scale(-1, 1, 0, 0);
```

Also, to avoid having mixed transforms and having to undo everything, just wrap them in a `SKAutoCanvasRestore` (or just use the `Save` and `Restore` methods):

```csharp
using(new SKAutoCanvasRestore(canvas, true))
{
   // transform and draw . . .
}
```
