### ISSUE TITLE
Where is SkiaSharp.Views.watchOS.SKCanvasView?

### ISSUE THREAD

**Issue by Happypig375** [mono/SkiaSharp#628]
### Description

There are no CanvasViews in SkiaSharp.Views.watchOS as opposed to SkiaSharp.Views.iOS/tvOS/Mac.

### Code

`SkiaSharp.Views.watchOS. //See intellisense`

### Expected Behavior

Some helper view will be present in SkiaSharp.watchOS.

### Actual Behavior

No helper views nor controllers are there.

### Basic Information

- Version with issue:  1.60.3
- IDE:  Visual Studio for Mac
- Platform Target Frameworks: 
  - watchOS:  default when creating project
- Target Devices:
  -   Apple Watch

**Comment by mattleibow** [comment]
Right now, there is no real plans to create a rendered view for watchOS. This is due to low demand and also, no easy way to create a watchOS view. Typically, the SkiaSharp views derive from some `UIView` or OpenGL view, but none exist on the watch.

I did some looking around and I found that people just created a `UIImage` and then used an image view to display it. You can do the same with SkiaSharp and the `SkiaSharp.Views.watchOS` namespace extension methods:

```csharp
// sue normal SkiaSharp
var bitmap = new SKBitmap(100, 100);
// … draw …

// use the extension methods to convert the SkiaSharp image to a watchOS image
var image = bitmap.ToUIImage(…);

// display
imageView.SetImage(image);
```

I have a full sample here: https://github.com/mono/SkiaSharp/blob/v1.60.3/samples/Basic/watchOS/SkiaSharpSample.OnWatchExtension/InterfaceController.cs

**Comment by mattleibow** [comment]
If there is a way to create a nice view that can be used, then feel free to re-open.
