### ISSUE TITLE
Change the native library names to libSkiaSharp

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#77]
I have just been working with @galvesribeiro to get SkiaSharp onto a ARM v6l Linux device (yay!) #18. One of the issues was that we had to re-build SkiaSharp just so that we could change the native library name in the `[DllImport]`. 

What are the opinions of changing the native library name to a uniform `libSkiaSharp` so that future Linux (or any other "normal" builds) can just use the Desktop assembly?

We might even remove the need for the .dll.config file currently. (just a guess)

**Comment by galvesribeiro** [comment]
![img_1789](https://cloud.githubusercontent.com/assets/4714040/15081055/3d4788ec-1397-11e6-9be7-5481ec17e39c.JPG)
![img_1787](https://cloud.githubusercontent.com/assets/4714040/15081058/3d4d3b5c-1397-11e6-8d46-881265fee7c2.JPG)
![img_1788](https://cloud.githubusercontent.com/assets/4714040/15081057/3d4995ec-1397-11e6-9a3a-236a022eef07.JPG)
![img_1792](https://cloud.githubusercontent.com/assets/4714040/15081056/3d481f1e-1397-11e6-9d90-b740400828e8.JPG)

And that is working as you can see! :)

**Comment by mattleibow** [comment]
Work being done in #81

**Comment by kekekeks** [comment]
Why not use `dlsym`/`GetProcAddress` and `Marshal.GetDelegateFromFunctionPtr` instead of `DllImport`? That will add a *lot* of flexibility in native library location like looking for correct CPU arch version in libSkiaSharp-x86.dll or libSkiaSharp-x64.dll depending on current platform. 

Something like that (MIT-licensed):
https://github.com/kekekeks/evhttp-sharp/blob/master/EvHttpSharp/Interop/LinuxLoader.cs
https://github.com/kekekeks/evhttp-sharp/blob/master/EvHttpSharp/Interop/OsxLoader.cs
https://github.com/kekekeks/evhttp-sharp/blob/master/EvHttpSharp/Interop/Win32Loader.cs

https://github.com/kekekeks/evhttp-sharp/blob/master/EvHttpSharp/Interop/Event.cs (usage)

**Comment by kekekeks** [comment]
The only issue that I see is iOS static linker, but I think that a custom dlsym (`skiasharp_dlsym` or something)  could be implemented in the native code. We did it this way in our old skia-based backend in avalonia(aka perspex) and it worked quite well.

**Comment by jameswalmsley** [comment]
Are there any instruction on how this was achieved. I want to run SkiaSharp on native Linux but intel.

**Comment by mattleibow** [comment]
@jameswalmsley I just use a default name of libSkiaSharp.[a/dll/so/dylib]

I do this in the https://github.com/mono/SkiaSharp/blob/v1.53.0/binding/Binding/SkiaApi.cs#L48-L62
You should be able to just `#if __LINUX__` or something. But, it should also fall back to the default `"libSkiaSharp"` and the mono runtime will automatically select the correct extension on the platform.
