### ISSUE TITLE
[BUG][macOS] AppKit.NSOpenGLPixelFormat: the native 'init*' method returned nil

### ISSUE THREAD

**Issue by praeclarum** [mono/SkiaSharp#977]
**Description**

`SKGLView` fails to initialize with the error **Could not initialize an instance of the type 'AppKit.NSOpenGLPixelFormat': the native 'init*' method returned nil.**

```
System.Exception: Could not initialize an instance of the type 'AppKit.NSOpenGLPixelFormat': the native 'init*' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
  at Foundation.NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector) [0x000b9] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.4.0.2/src/Xamarin.Mac/Foundation/NSObject2.cs:504 
  at Foundation.NSObject.InitializeHandle (System.IntPtr handle) [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.4.0.2/src/Xamarin.Mac/Foundation/NSObject2.cs:480 
  at AppKit.NSOpenGLPixelFormat..ctor (System.UInt32[] attribs) [0x0005f] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.4.0.2/src/Xamarin.Mac/AppKit/NSOpenGLPixelFormat.cs:69 
  at AppKit.NSOpenGLPixelFormat..ctor (System.Object[] attribs) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.4.0.2/src/Xamarin.Mac/AppKit/NSOpenGLPixelFormat.cs:150 
  at SkiaSharp.Views.Mac.SKGLView.Initialize () [0x000af] in <08acf5ba669b46b0a186cc90d42326cf>:0 
  at SkiaSharp.Views.Mac.SKGLView.AwakeFromNib () [0x00000] in <08acf5ba669b46b0a186cc90d42326cf>:0 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.4.0.2/src/Xamarin.Mac/AppKit/NSApplication.cs:100 
  at Circuit.Mac.MainClass.Main (System.String[] args) [0x00007] in /Users/fak/Dropbox/Projects/Circuit/CircuitMac/Main.cs:14 
```

**Code**

```csharp
new SkiaSharp.Views.Mac.SKGLView ()
```

**Expected Behavior**

The GL view works as normal.

**Actual Behavior**

The above exception

**Basic Information**

- Version with issue:  1.68.1-rc.153
- Last known good version:  1.68.0
- IDE:  Visual Studio for Mac
- Platform Target Frameworks:
  - macOS:  10.11

**Comment by praeclarum** [comment]
It also crashes on macOS 10.9 - Mavericks.

**Comment by praeclarum** [comment]
It looks like you're supposed to expect errors (null returns) and adjust the attributes until it works :-/ according to: https://developer.apple.com/documentation/appkit/nsopenglpixelformat/1436219-initwithattributes?language=objc

**Comment by praeclarum** [comment]
This may be a less severe bug than I first thought.

Looks like it's the "Accelerated" attribute causing trouble. However, I imagine most macOS 10.9+ systems have accelerated. I think I'll still make a PR to fix this.

**Comment by mattleibow** [comment]
Thanks for the research. I am not a total fan of the try until it works that we have with OpenGL. But, I suppose that is what must be done - if it ain't there, we can't use it.

**Comment by mattleibow** [comment]
Just on that... Are use using a system that doesn't support the Accelerated?

**Comment by praeclarum** [comment]
@mattleibow The documentation specifically says you *should* try until it works - its how the API was designed. Don't anthropomorphize computers ;-D

**Comment by mattleibow** [comment]
Yeah, I know. But we got AI! They said it was the future! I thought we were in a modern world with "machine learning" 😜 The machines must learn that I want to draw images, not try and check for features. And then it must draw it very fast.

You still got that PR in progress? Was it just a case of trying again without Accelerated or were there other flags that needed removing?

**Comment by v-vasilev-synergy** [comment]
This crashes for me too when running Mac on a Virtual Machine (where there's no hardware acceleration available due to display adapter not working with VM)
What's weird is that the same parameters used to work on 1.68.0

Turns out it's initializing the attributes as object[]
https://github.com/mono/SkiaSharp/blob/v1.68.1.1/source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs#L50

Not NSOpenGLPixelFormatAttribute[]
https://github.com/mono/SkiaSharp/blob/v1.68.0/source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs#L47

That doesn't work - once I modify a local copy of SKGLView and initialize the array as NSOpenGLPixelFormatAttribute[], it works on my VM - object[] does not.
There may be something going wrong while converting the parameters.
Can we switch back to NSOpenGLPixelFormatAttribute in the next version?

**Comment by MatheMagick** [comment]
This crashes for me too when running Mac on a Virtual Machine (where there's no hardware acceleration available due to display adapter not working with VM)
What's weird is that the same parameters used to work on 1.68.0

Turns out it's initializing the attributes as object[]
https://github.com/mono/SkiaSharp/blob/v1.68.1.1/source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs#L50

Not NSOpenGLPixelFormatAttribute[]
https://github.com/mono/SkiaSharp/blob/v1.68.0/source/SkiaSharp.Views/SkiaSharp.Views.Mac/SKGLView.cs#L47

That doesn't work - once I modify a local copy of SKGLView and initialize the array as NSOpenGLPixelFormatAttribute[], it works on my VM - object[] does not.
There may be something going wrong while converting the parameters.
Can we switch back to NSOpenGLPixelFormatAttribute in the next version, since it seems to fix the issue?

**Comment by mattleibow** [comment]
That is very weird. I'll check what is happening in Xamarin.Mac and see if there is some funny business.

I'll see what I can do for a release ASAP to fix this.

**Comment by mattleibow** [comment]
Closing this with #1083 as that seems to be the only change made. We can always reopen this.

I think the issue was that the `NSOpenGLPixelFormatAttribute[]` required a null-termination, and the `object[]` did not (added in the internal conversion). Seems having a double null-termination broke a few more things than it probably should have.
